export interface QCRun {
  id: string;
  date: string;
  shift: "morning" | "afternoon" | "night";
  analyte: string; // e.g. "glu" or "hb"
  analyteName: string; // e.g. "Glucose" or "Hemoglobin"
  lotNumber: string;
  level: "Level 1" | "Level 2" | "Level 3";
  value: number;
  mean: number;
  sd: number;
  status: "pass" | "warning" | "fail";
  rulesTriggered?: string[];
  runBy: string;
  correctiveAction?: string;
}

// Helper to generate ISO date strings relative to today
const daysAgo = (n: number, hour: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
};

export const SEED_QC_RUNS: QCRun[] = [
  // GLUCOSE QC RUNS (Analyte: Glucose, Mean: 100, SD: 5)
  {
    id: "QC-GLU-001",
    date: daysAgo(5, 8),
    shift: "morning",
    analyte: "glu",
    analyteName: "Glucose",
    lotNumber: "LOT-GLU-A5",
    level: "Level 2",
    value: 99.2,
    mean: 100,
    sd: 5,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-GLU-002",
    date: daysAgo(5, 16),
    shift: "afternoon",
    analyte: "glu",
    analyteName: "Glucose",
    lotNumber: "LOT-GLU-A5",
    level: "Level 2",
    value: 101.5,
    mean: 100,
    sd: 5,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-GLU-003",
    date: daysAgo(4, 8),
    shift: "morning",
    analyte: "glu",
    analyteName: "Glucose",
    lotNumber: "LOT-GLU-A5",
    level: "Level 2",
    value: 102.8,
    mean: 100,
    sd: 5,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-GLU-004",
    date: daysAgo(4, 16),
    shift: "afternoon",
    analyte: "glu",
    analyteName: "Glucose",
    lotNumber: "LOT-GLU-A5",
    level: "Level 2",
    value: 111.2, // Warning (> 2SD)
    mean: 100,
    sd: 5,
    status: "warning",
    rulesTriggered: ["1_2s Rule Warning"],
    runBy: "J. Mensah",
  },
  {
    id: "QC-GLU-005",
    date: daysAgo(3, 8),
    shift: "morning",
    analyte: "glu",
    analyteName: "Glucose",
    lotNumber: "LOT-GLU-A5",
    level: "Level 2",
    value: 98.4,
    mean: 100,
    sd: 5,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-GLU-006",
    date: daysAgo(3, 16),
    shift: "afternoon",
    analyte: "glu",
    analyteName: "Glucose",
    lotNumber: "LOT-GLU-A5",
    level: "Level 2",
    value: 97.1,
    mean: 100,
    sd: 5,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-GLU-007",
    date: daysAgo(2, 8),
    shift: "morning",
    analyte: "glu",
    analyteName: "Glucose",
    lotNumber: "LOT-GLU-A5",
    level: "Level 2",
    value: 116.5, // Fail (> 3SD)
    mean: 100,
    sd: 5,
    status: "fail",
    rulesTriggered: ["1_3s Rule Violation"],
    runBy: "J. Mensah",
    correctiveAction: "Realigned and recalibrated analyzer. Repeated run.",
  },
  {
    id: "QC-GLU-008",
    date: daysAgo(2, 9),
    shift: "morning",
    analyte: "glu",
    analyteName: "Glucose",
    lotNumber: "LOT-GLU-A5",
    level: "Level 2",
    value: 100.2, // Repeat run after calibration
    mean: 100,
    sd: 5,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-GLU-009",
    date: daysAgo(2, 16),
    shift: "afternoon",
    analyte: "glu",
    analyteName: "Glucose",
    lotNumber: "LOT-GLU-A5",
    level: "Level 2",
    value: 102.1,
    mean: 100,
    sd: 5,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-GLU-010",
    date: daysAgo(1, 8),
    shift: "morning",
    analyte: "glu",
    analyteName: "Glucose",
    lotNumber: "LOT-GLU-A5",
    level: "Level 2",
    value: 88.5, // Warning (< -2SD)
    mean: 100,
    sd: 5,
    status: "warning",
    rulesTriggered: ["1_2s Rule Warning"],
    runBy: "J. Mensah",
  },
  {
    id: "QC-GLU-011",
    date: daysAgo(1, 16),
    shift: "afternoon",
    analyte: "glu",
    analyteName: "Glucose",
    lotNumber: "LOT-GLU-A5",
    level: "Level 2",
    value: 99.7,
    mean: 100,
    sd: 5,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-GLU-012",
    date: daysAgo(0, 8),
    shift: "morning",
    analyte: "glu",
    analyteName: "Glucose",
    lotNumber: "LOT-GLU-A5",
    level: "Level 2",
    value: 100.8,
    mean: 100,
    sd: 5,
    status: "pass",
    runBy: "J. Mensah",
  },

  // HEMOGLOBIN QC RUNS (Analyte: Hemoglobin, Mean: 12.0, SD: 0.4)
  {
    id: "QC-HB-001",
    date: daysAgo(5, 8),
    shift: "morning",
    analyte: "hb",
    analyteName: "Hemoglobin",
    lotNumber: "LOT-HEM-H2",
    level: "Level 1",
    value: 12.1,
    mean: 12.0,
    sd: 0.4,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-HB-002",
    date: daysAgo(5, 16),
    shift: "afternoon",
    analyte: "hb",
    analyteName: "Hemoglobin",
    lotNumber: "LOT-HEM-H2",
    level: "Level 1",
    value: 11.9,
    mean: 12.0,
    sd: 0.4,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-HB-003",
    date: daysAgo(4, 8),
    shift: "morning",
    analyte: "hb",
    analyteName: "Hemoglobin",
    lotNumber: "LOT-HEM-H2",
    level: "Level 1",
    value: 12.9, // Warning (> 2SD)
    mean: 12.0,
    sd: 0.4,
    status: "warning",
    rulesTriggered: ["1_2s Rule Warning"],
    runBy: "J. Mensah",
  },
  {
    id: "QC-HB-004",
    date: daysAgo(4, 16),
    shift: "afternoon",
    analyte: "hb",
    analyteName: "Hemoglobin",
    lotNumber: "LOT-HEM-H2",
    level: "Level 1",
    value: 12.2,
    mean: 12.0,
    sd: 0.4,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-HB-005",
    date: daysAgo(3, 8),
    shift: "morning",
    analyte: "hb",
    analyteName: "Hemoglobin",
    lotNumber: "LOT-HEM-H2",
    level: "Level 1",
    value: 12.0,
    mean: 12.0,
    sd: 0.4,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-HB-006",
    date: daysAgo(3, 16),
    shift: "afternoon",
    analyte: "hb",
    analyteName: "Hemoglobin",
    lotNumber: "LOT-HEM-H2",
    level: "Level 1",
    value: 10.7, // Fail (> 3SD)
    mean: 12.0,
    sd: 0.4,
    status: "fail",
    rulesTriggered: ["1_3s Rule Violation"],
    runBy: "J. Mensah",
    correctiveAction: "Replaced Hemolyzing Reagent lot. Repeated control.",
  },
  {
    id: "QC-HB-007",
    date: daysAgo(3, 17),
    shift: "afternoon",
    analyte: "hb",
    analyteName: "Hemoglobin",
    lotNumber: "LOT-HEM-H2",
    level: "Level 1",
    value: 11.9, // Repeat pass
    mean: 12.0,
    sd: 0.4,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-HB-008",
    date: daysAgo(2, 8),
    shift: "morning",
    analyte: "hb",
    analyteName: "Hemoglobin",
    lotNumber: "LOT-HEM-H2",
    level: "Level 1",
    value: 12.1,
    mean: 12.0,
    sd: 0.4,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-HB-009",
    date: daysAgo(2, 16),
    shift: "afternoon",
    analyte: "hb",
    analyteName: "Hemoglobin",
    lotNumber: "LOT-HEM-H2",
    level: "Level 1",
    value: 11.1, // Warning (< -2SD)
    mean: 12.0,
    sd: 0.4,
    status: "warning",
    rulesTriggered: ["1_2s Rule Warning"],
    runBy: "J. Mensah",
  },
  {
    id: "QC-HB-010",
    date: daysAgo(1, 8),
    shift: "morning",
    analyte: "hb",
    analyteName: "Hemoglobin",
    lotNumber: "LOT-HEM-H2",
    level: "Level 1",
    value: 12.2,
    mean: 12.0,
    sd: 0.4,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-HB-011",
    date: daysAgo(1, 16),
    shift: "afternoon",
    analyte: "hb",
    analyteName: "Hemoglobin",
    lotNumber: "LOT-HEM-H2",
    level: "Level 1",
    value: 11.8,
    mean: 12.0,
    sd: 0.4,
    status: "pass",
    runBy: "J. Mensah",
  },
  {
    id: "QC-HB-012",
    date: daysAgo(0, 8),
    shift: "morning",
    analyte: "hb",
    analyteName: "Hemoglobin",
    lotNumber: "LOT-HEM-H2",
    level: "Level 1",
    value: 12.0,
    mean: 12.0,
    sd: 0.4,
    status: "pass",
    runBy: "J. Mensah",
  },
];
