// Mock data for the Medora Lab portal
// Shapes align with Supabase tables: lab_orders, lab_results, lab_catalog

export const SECTIONS = [
  { id: "hematology", label: "Hematology" },
  { id: "biochemistry", label: "Biochemistry" },
  { id: "microbiology", label: "Microbiology" },
  { id: "serology", label: "Serology" },
  { id: "urinalysis", label: "Urinalysis" },
  { id: "endocrinology", label: "Endocrinology" },
];

// Lab test catalog
export const LAB_CATALOG = [
  {
    code: "CBC",
    name: "Complete Blood Count",
    section: "hematology",
    sample_type: "Whole blood (EDTA)",
    tube: "Lavender",
    tat_hours: 2,
    fasting: false,
    price: 18,
    parameters: [
      { key: "WBC", label: "White Blood Cells", unit: "10^9/L", ref_low: 4.0, ref_high: 11.0, critical_low: 2.0, critical_high: 30.0 },
      { key: "RBC", label: "Red Blood Cells", unit: "10^12/L", ref_low: 4.2, ref_high: 5.9 },
      { key: "HGB", label: "Hemoglobin", unit: "g/dL", ref_low: 12.0, ref_high: 17.5, critical_low: 7.0, critical_high: 20.0 },
      { key: "HCT", label: "Hematocrit", unit: "%", ref_low: 36, ref_high: 52 },
      { key: "PLT", label: "Platelets", unit: "10^9/L", ref_low: 150, ref_high: 400, critical_low: 50, critical_high: 1000 },
    ],
  },
  {
    code: "LIPID",
    name: "Lipid Panel",
    section: "biochemistry",
    sample_type: "Serum",
    tube: "Gold (SST)",
    tat_hours: 4,
    fasting: true,
    price: 32,
    parameters: [
      { key: "TC", label: "Total Cholesterol", unit: "mg/dL", ref_low: 0, ref_high: 200 },
      { key: "LDL", label: "LDL Cholesterol", unit: "mg/dL", ref_low: 0, ref_high: 130 },
      { key: "HDL", label: "HDL Cholesterol", unit: "mg/dL", ref_low: 40, ref_high: 100 },
      { key: "TG", label: "Triglycerides", unit: "mg/dL", ref_low: 0, ref_high: 150 },
    ],
  },
  {
    code: "HBA1C",
    name: "HbA1c",
    section: "biochemistry",
    sample_type: "Whole blood (EDTA)",
    tube: "Lavender",
    tat_hours: 4,
    fasting: false,
    price: 24,
    parameters: [
      { key: "HBA1C", label: "Glycated Hemoglobin", unit: "%", ref_low: 4.0, ref_high: 5.6, critical_high: 14.0 },
    ],
  },
  {
    code: "TFT",
    name: "Thyroid Function Test",
    section: "endocrinology",
    sample_type: "Serum",
    tube: "Gold (SST)",
    tat_hours: 6,
    fasting: false,
    price: 38,
    parameters: [
      { key: "TSH", label: "TSH", unit: "mIU/L", ref_low: 0.4, ref_high: 4.0 },
      { key: "T3", label: "Free T3", unit: "pg/mL", ref_low: 2.3, ref_high: 4.2 },
      { key: "T4", label: "Free T4", unit: "ng/dL", ref_low: 0.8, ref_high: 1.8 },
    ],
  },
  {
    code: "UA",
    name: "Urinalysis",
    section: "urinalysis",
    sample_type: "Urine (mid-stream)",
    tube: "Yellow cup",
    tat_hours: 2,
    fasting: false,
    price: 14,
    parameters: [
      { key: "COLOR", label: "Color", unit: "", ref_text: "Yellow" },
      { key: "PROT", label: "Protein", unit: "", ref_text: "Negative" },
      { key: "GLU", label: "Glucose", unit: "", ref_text: "Negative" },
      { key: "PH", label: "pH", unit: "", ref_low: 4.5, ref_high: 8.0 },
    ],
  },
  {
    code: "LFT",
    name: "Liver Function Test",
    section: "biochemistry",
    sample_type: "Serum",
    tube: "Gold (SST)",
    tat_hours: 4,
    fasting: false,
    price: 36,
    parameters: [
      { key: "ALT", label: "ALT (SGPT)", unit: "U/L", ref_low: 7, ref_high: 56, critical_high: 500 },
      { key: "AST", label: "AST (SGOT)", unit: "U/L", ref_low: 10, ref_high: 40, critical_high: 500 },
      { key: "ALP", label: "Alkaline Phosphatase", unit: "U/L", ref_low: 44, ref_high: 147 },
      { key: "TBIL", label: "Total Bilirubin", unit: "mg/dL", ref_low: 0.1, ref_high: 1.2 },
      { key: "ALB", label: "Albumin", unit: "g/dL", ref_low: 3.5, ref_high: 5.0 },
    ],
  },
];

export const findCatalog = (code) => LAB_CATALOG.find((t) => t.code === code);

// Mock patients
export const PATIENTS = [
  { id: "p-1001", name: "Amara Okafor", mrn: "MR-23841", age: 34, sex: "F", phone: "+1 555-0118" },
  { id: "p-1002", name: "Ravi Sundaram", mrn: "MR-23912", age: 58, sex: "M", phone: "+1 555-0224" },
  { id: "p-1003", name: "Sofia Marchetti", mrn: "MR-24017", age: 27, sex: "F", phone: "+1 555-0339" },
  { id: "p-1004", name: "Thabo Mokoena", mrn: "MR-24108", age: 45, sex: "M", phone: "+1 555-0441" },
  { id: "p-1005", name: "Yuki Tanaka", mrn: "MR-24205", age: 62, sex: "F", phone: "+1 555-0552" },
  { id: "p-1006", name: "Diego Hernández", mrn: "MR-24317", age: 39, sex: "M", phone: "+1 555-0664" },
  { id: "p-1007", name: "Linnea Bergström", mrn: "MR-24433", age: 51, sex: "F", phone: "+1 555-0775" },
  { id: "p-1008", name: "Kwame Asante", mrn: "MR-24528", age: 29, sex: "M", phone: "+1 555-0886" },
];

// Mock doctors
export const DOCTORS = [
  { id: "d-201", name: "Dr. Mei Tan", specialty: "Internal Medicine" },
  { id: "d-202", name: "Dr. Adebayo Owens", specialty: "Endocrinology" },
  { id: "d-203", name: "Dr. Priya Iyer", specialty: "Cardiology" },
  { id: "d-204", name: "Dr. Henrik Vogel", specialty: "Family Medicine" },
];

const now = Date.now();
const minutesAgo = (m) => new Date(now - m * 60_000).toISOString();
const hoursAgo = (h) => new Date(now - h * 3_600_000).toISOString();

// Seeded mock orders
export const SEED_ORDERS = [
  {
    id: "LO-100245",
    accession: "ACC-A4421",
    patient_id: "p-1001",
    doctor_id: "d-201",
    test_code: "CBC",
    test_name: "Complete Blood Count",
    status: "ordered",
    priority: "stat",
    source: "doctor",
    notes: "Suspected anemia, fatigue 3 weeks.",
    fasting: false,
    ordered_at: minutesAgo(8),
    collected_at: null,
    completed_at: null,
    validated_at: null,
    released_at: null,
    cancelled_at: null,
    cancel_reason: null,
    assigned_to: null,
    collector: null,
    history: [
      { at: minutesAgo(8), actor: "Dr. Mei Tan", action: "Order placed", note: "STAT request" },
    ],
  },
  {
    id: "LO-100244",
    accession: "ACC-A4420",
    patient_id: "p-1002",
    doctor_id: "d-202",
    test_code: "HBA1C",
    test_name: "HbA1c",
    status: "ordered",
    priority: "routine",
    source: "doctor",
    notes: "Quarterly diabetic follow-up.",
    fasting: false,
    ordered_at: minutesAgo(42),
    collected_at: null,
    completed_at: null,
    validated_at: null,
    released_at: null,
    cancelled_at: null,
    cancel_reason: null,
    assigned_to: null,
    collector: null,
    history: [{ at: minutesAgo(42), actor: "Dr. Adebayo Owens", action: "Order placed" }],
  },
  {
    id: "LO-100243",
    accession: "ACC-A4419",
    patient_id: "p-1003",
    doctor_id: "d-204",
    test_code: "LIPID",
    test_name: "Lipid Panel",
    status: "ordered",
    priority: "urgent",
    source: "reception",
    notes: "Pre-op screening.",
    fasting: true,
    ordered_at: minutesAgo(70),
    collected_at: null,
    completed_at: null,
    validated_at: null,
    released_at: null,
    cancelled_at: null,
    cancel_reason: null,
    assigned_to: null,
    collector: null,
    history: [{ at: minutesAgo(70), actor: "Reception (walk-in)", action: "Order placed" }],
  },
  {
    id: "LO-100240",
    accession: "ACC-A4416",
    patient_id: "p-1004",
    doctor_id: "d-201",
    test_code: "LFT",
    test_name: "Liver Function Test",
    status: "collected",
    priority: "routine",
    source: "doctor",
    notes: "Suspected hepatitis.",
    fasting: false,
    ordered_at: hoursAgo(2),
    collected_at: minutesAgo(35),
    completed_at: null,
    validated_at: null,
    released_at: null,
    cancelled_at: null,
    cancel_reason: null,
    assigned_to: null,
    collector: "Nia Brooks (Phleb)",
    history: [
      { at: hoursAgo(2), actor: "Dr. Mei Tan", action: "Order placed" },
      { at: minutesAgo(35), actor: "Nia Brooks", action: "Sample collected" },
    ],
  },
  {
    id: "LO-100239",
    accession: "ACC-A4415",
    patient_id: "p-1005",
    doctor_id: "d-203",
    test_code: "TFT",
    test_name: "Thyroid Function Test",
    status: "collected",
    priority: "routine",
    source: "doctor",
    notes: "Fatigue + weight gain workup.",
    fasting: false,
    ordered_at: hoursAgo(3),
    collected_at: minutesAgo(55),
    completed_at: null,
    validated_at: null,
    released_at: null,
    cancelled_at: null,
    cancel_reason: null,
    assigned_to: null,
    collector: "Nia Brooks (Phleb)",
    history: [
      { at: hoursAgo(3), actor: "Dr. Priya Iyer", action: "Order placed" },
      { at: minutesAgo(55), actor: "Nia Brooks", action: "Sample collected" },
    ],
  },
  {
    id: "LO-100236",
    accession: "ACC-A4412",
    patient_id: "p-1006",
    doctor_id: "d-204",
    test_code: "CBC",
    test_name: "Complete Blood Count",
    status: "processing",
    priority: "routine",
    source: "doctor",
    notes: "Routine annual checkup.",
    fasting: false,
    ordered_at: hoursAgo(5),
    collected_at: hoursAgo(4),
    completed_at: null,
    validated_at: null,
    released_at: null,
    cancelled_at: null,
    cancel_reason: null,
    assigned_to: "Tech: Marcus Lin",
    collector: "Nia Brooks (Phleb)",
    results: {
      WBC: "7.2",
      RBC: "4.8",
      HGB: "14.1",
      HCT: "42",
      PLT: "260",
    },
    history: [
      { at: hoursAgo(5), actor: "Dr. Henrik Vogel", action: "Order placed" },
      { at: hoursAgo(4), actor: "Nia Brooks", action: "Sample collected" },
      { at: hoursAgo(3), actor: "Marcus Lin", action: "Processing started" },
    ],
  },
  {
    id: "LO-100231",
    accession: "ACC-A4408",
    patient_id: "p-1007",
    doctor_id: "d-202",
    test_code: "HBA1C",
    test_name: "HbA1c",
    status: "validated",
    priority: "routine",
    source: "doctor",
    notes: "Diabetes follow-up.",
    fasting: false,
    ordered_at: hoursAgo(8),
    collected_at: hoursAgo(7),
    completed_at: hoursAgo(4),
    validated_at: hoursAgo(3),
    released_at: hoursAgo(3),
    cancelled_at: null,
    cancel_reason: null,
    assigned_to: "Tech: Marcus Lin",
    collector: "Nia Brooks (Phleb)",
    validated_by: "Dr. Sasha Pereira (Supervisor)",
    results: {
      HBA1C: "8.4",
    },
    history: [
      { at: hoursAgo(8), actor: "Dr. Adebayo Owens", action: "Order placed" },
      { at: hoursAgo(7), actor: "Nia Brooks", action: "Sample collected" },
      { at: hoursAgo(4), actor: "Marcus Lin", action: "Results entered" },
      { at: hoursAgo(3), actor: "Dr. Sasha Pereira", action: "Validated & released" },
    ],
  },
  {
    id: "LO-100228",
    accession: "ACC-A4405",
    patient_id: "p-1008",
    doctor_id: "d-203",
    test_code: "LIPID",
    test_name: "Lipid Panel",
    status: "validated",
    priority: "routine",
    source: "doctor",
    notes: "Cardio risk assessment.",
    fasting: true,
    ordered_at: hoursAgo(10),
    collected_at: hoursAgo(9),
    completed_at: hoursAgo(6),
    validated_at: hoursAgo(5),
    released_at: hoursAgo(5),
    cancelled_at: null,
    cancel_reason: null,
    assigned_to: "Tech: Imani Russo",
    collector: "Nia Brooks (Phleb)",
    validated_by: "Dr. Sasha Pereira (Supervisor)",
    results: {
      TC: "188",
      LDL: "118",
      HDL: "52",
      TG: "132",
    },
    history: [
      { at: hoursAgo(10), actor: "Dr. Priya Iyer", action: "Order placed" },
      { at: hoursAgo(9), actor: "Nia Brooks", action: "Sample collected" },
      { at: hoursAgo(6), actor: "Imani Russo", action: "Results entered" },
      { at: hoursAgo(5), actor: "Dr. Sasha Pereira", action: "Validated & released" },
    ],
  },
];

export const STAFF = [
  { id: "s-1", name: "Marcus Lin", role: "lab_technician", section: "hematology", shift: "Morning" },
  { id: "s-2", name: "Imani Russo", role: "lab_technician", section: "biochemistry", shift: "Morning" },
  { id: "s-3", name: "Nia Brooks", role: "phlebotomist", section: "collection", shift: "Morning" },
  { id: "s-4", name: "Dr. Sasha Pereira", role: "lab_supervisor", section: "all", shift: "Day" },
];

export const HOSPITAL = {
  name: "Medora Health Sciences",
  tagline: "Integrated diagnostic care",
  address: "412 Linden Way · Suite 2200 · Auckland 1010",
  phone: "+64 9 555 0188",
  email: "lab@medora.health",
  lab_director: "Dr. Sasha Pereira, MD · Lab Director",
  clia: "CLIA #74D2204918",
};
