import type { SpecialtyId } from "@/lib/specialties/types";
import type { AnatomyView, BodyMarker } from "@/lib/shared/body-anatomy";
import type { ViewPreset } from "@/lib/shared/anatomy-systems";

/** Per-specialty 3D anatomy focus — same atlas GLB, clinically framed per category */
export type SpecialtyAnatomyFocus = {
  specialtyId: SpecialtyId;
  title: string;
  subtitle: string;
  /** Keywords matched against mesh labels for auto-highlight */
  focusKeywords: string[];
  defaultView: AnatomyView;
  defaultPreset: ViewPreset;
  /** Orbit target on centered atlas (x, y, z) */
  cameraTarget: [number, number, number];
  cameraDistance: number;
  /** Suggested clinical structures to mark */
  seedLabels: string[];
  structures: { name: string; note: string }[];
};

export const SPECIALTY_ANATOMY: Record<SpecialtyId, SpecialtyAnatomyFocus> = {
  ophthalmology: {
    specialtyId: "ophthalmology",
    title: "Eye & orbit anatomy",
    subtitle: "Orbit, globe, extraocular muscles, optic pathway",
    focusKeywords: ["eye", "orbit", "optic", "oculi", "rectus", "oblique", "lacrimal", "sclera", "cornea"],
    defaultView: "external-front",
    defaultPreset: "surface",
    cameraTarget: [0, 0.68, 0.08],
    cameraDistance: 0.55,
    seedLabels: ["Left orbit", "Right orbit", "Optic nerve"],
    structures: [
      { name: "Globe / cornea", note: "Anterior segment exam" },
      { name: "Extraocular muscles", note: "Motility / squint" },
      { name: "Optic nerve", note: "Disc / RNFL correlation" },
      { name: "Orbit", note: "Trauma / thyroid eye disease" },
    ],
  },
  cardiology: {
    specialtyId: "cardiology",
    title: "Cardiac & vascular anatomy",
    subtitle: "Heart silhouette, great vessels, coronary territory",
    focusKeywords: ["heart", "aorta", "coronar", "cardiac", "ventric", "atrium", "pulmonary", "vena"],
    defaultView: "external-front",
    defaultPreset: "vascular",
    cameraTarget: [0.02, 0.32, 0.06],
    cameraDistance: 0.95,
    seedLabels: ["Heart", "Aorta", "Left coronary territory"],
    structures: [
      { name: "Heart", note: "Auscultation / echo windows" },
      { name: "Aorta / arch", note: "Aneurysm / dissection risk" },
      { name: "Carotids", note: "Stroke workup" },
      { name: "Coronary beds", note: "CAD / PCI planning" },
    ],
  },
  pediatrics: {
    specialtyId: "pediatrics",
    title: "Pediatric body map",
    subtitle: "Growth regions, airway, abdomen — full pediatric survey",
    focusKeywords: ["skull", "rib", "abdomen", "femur", "spine", "lung"],
    defaultView: "external-front",
    defaultPreset: "surface",
    cameraTarget: [0, 0.15, 0],
    cameraDistance: 2.4,
    seedLabels: ["Chest", "Abdomen", "Head"],
    structures: [
      { name: "Head / fontanelle zone", note: "Development / trauma" },
      { name: "Chest / airway", note: "Wheeze / pneumonia" },
      { name: "Abdomen", note: "GE / acute abdomen" },
      { name: "Long bones", note: "Growth / fracture" },
    ],
  },
  orthopedics: {
    specialtyId: "orthopedics",
    title: "Musculoskeletal anatomy",
    subtitle: "Bones, joints, muscle groups — fracture & sports focus",
    focusKeywords: ["femur", "tibia", "humerus", "radius", "ulna", "pelvis", "spine", "knee", "shoulder", "hip", "clavicle", "scapula", "vertebra"],
    defaultView: "external-front",
    defaultPreset: "skeleton",
    cameraTarget: [0, 0.05, 0],
    cameraDistance: 2.2,
    seedLabels: ["Knee", "Hip", "Lumbar spine"],
    structures: [
      { name: "Long bones", note: "Fracture classification" },
      { name: "Joints", note: "OA / instability" },
      { name: "Spine", note: "Disc / trauma" },
      { name: "Shoulder girdle", note: "Rotator cuff / dislocation" },
    ],
  },
  neurology: {
    specialtyId: "neurology",
    title: "Neuroanatomy",
    subtitle: "Brain, cranial nerves, cord & peripheral pathways",
    focusKeywords: ["brain", "skull", "nerve", "spinal", "cranial", "plexus", "cerebr", "cerebell"],
    defaultView: "external-front",
    defaultPreset: "nervous",
    cameraTarget: [0, 0.62, 0],
    cameraDistance: 0.85,
    seedLabels: ["Brain", "Cervical cord", "Sciatic pathway"],
    structures: [
      { name: "Brain / skull", note: "Stroke / seizure focus" },
      { name: "Cranial nerves", note: "CN exam correlation" },
      { name: "Spinal cord", note: "Myelopathy" },
      { name: "Peripheral nerves", note: "Neuropathy / radiculopathy" },
    ],
  },
  dermatology: {
    specialtyId: "dermatology",
    title: "Skin surface map",
    subtitle: "Dermatomes & regional distribution for rashes",
    focusKeywords: ["skin", "muscle", "face", "scalp", "hand", "foot"],
    defaultView: "external-front",
    defaultPreset: "surface",
    cameraTarget: [0, 0.2, 0.05],
    cameraDistance: 2.0,
    seedLabels: ["Face", "Trunk", "Extremities"],
    structures: [
      { name: "Face / scalp", note: "Acne / alopecia / rosacea" },
      { name: "Trunk", note: "Eczema / psoriasis plaques" },
      { name: "Flexures", note: "Intertrigo / atopic" },
      { name: "Hands / feet", note: "Tinea / contact derm" },
    ],
  },
  ent: {
    specialtyId: "ent",
    title: "ENT / head–neck anatomy",
    subtitle: "Ear, nose, throat, sinuses & neck nodes",
    focusKeywords: ["ear", "nose", "nasal", "throat", "larynx", "pharynx", "mandible", "maxilla", "thyroid", "neck", "temporal"],
    defaultView: "external-front",
    defaultPreset: "surface",
    cameraTarget: [0, 0.62, 0.1],
    cameraDistance: 0.7,
    seedLabels: ["Ear", "Nose / sinuses", "Neck"],
    structures: [
      { name: "External / middle ear", note: "Otitis / hearing" },
      { name: "Nose / sinuses", note: "Sinusitis / polyps" },
      { name: "Pharynx / larynx", note: "Tonsillitis / hoarseness" },
      { name: "Neck nodes", note: "Lymphadenopathy" },
    ],
  },
  gastroenterology: {
    specialtyId: "gastroenterology",
    title: "GI & abdominal anatomy",
    subtitle: "Stomach, bowel, liver, pancreas regions",
    focusKeywords: ["liver", "stomach", "intestin", "colon", "pancrea", "abdomen", "spleen", "gall"],
    defaultView: "external-front",
    defaultPreset: "inside",
    cameraTarget: [0.02, 0.05, 0.04],
    cameraDistance: 1.1,
    seedLabels: ["Liver", "Stomach", "Colon"],
    structures: [
      { name: "Upper GI", note: "GERD / ulcer / bleed" },
      { name: "Liver / biliary", note: "Hepatitis / stones" },
      { name: "Pancreas", note: "Pancreatitis" },
      { name: "Colon / rectum", note: "IBD / polyps" },
    ],
  },
  nephrology: {
    specialtyId: "nephrology",
    title: "Renal & urinary anatomy",
    subtitle: "Kidneys, ureters, bladder territory",
    focusKeywords: ["kidney", "renal", "ureter", "bladder", "adrenal"],
    defaultView: "external-back",
    defaultPreset: "inside",
    cameraTarget: [0, 0.08, -0.02],
    cameraDistance: 1.15,
    seedLabels: ["Left kidney", "Right kidney", "Bladder"],
    structures: [
      { name: "Kidneys", note: "CKD / stone / infection" },
      { name: "Ureters", note: "Obstruction" },
      { name: "Bladder", note: "LUTS / UTI" },
      { name: "Access sites", note: "AVF / catheter planning" },
    ],
  },
  pulmonology: {
    specialtyId: "pulmonology",
    title: "Respiratory anatomy",
    subtitle: "Lungs, airways, thorax & diaphragm",
    focusKeywords: ["lung", "pulmo", "bronch", "rib", "thorax", "diaphragm", "trachea", "pleura"],
    defaultView: "external-front",
    defaultPreset: "inside",
    cameraTarget: [0, 0.28, 0.05],
    cameraDistance: 1.0,
    seedLabels: ["Left lung", "Right lung", "Trachea"],
    structures: [
      { name: "Lungs / lobes", note: "Pneumonia / ILD" },
      { name: "Airways", note: "Asthma / COPD" },
      { name: "Pleura", note: "Effusion / pneumothorax" },
      { name: "Diaphragm", note: "Breathing mechanics" },
    ],
  },
  oncology: {
    specialtyId: "oncology",
    title: "Oncology staging map",
    subtitle: "Primary sites, nodes & common metastatic beds",
    focusKeywords: ["lymph", "liver", "lung", "bone", "brain", "breast", "colon"],
    defaultView: "external-front",
    defaultPreset: "inside",
    cameraTarget: [0, 0.15, 0],
    cameraDistance: 2.0,
    seedLabels: ["Primary site", "Nodal basin", "Met bed"],
    structures: [
      { name: "Primary organ", note: "T staging" },
      { name: "Regional nodes", note: "N staging" },
      { name: "Liver / lung / bone", note: "M staging" },
      { name: "CNS", note: "Brain mets screen" },
    ],
  },
  obgyn: {
    specialtyId: "obgyn",
    title: "Pelvic & obstetric anatomy",
    subtitle: "Uterus, adnexa, pelvis & fetal lie context",
    focusKeywords: ["pelvis", "uterus", "ovary", "vagina", "sacrum", "ilium", "pubis"],
    defaultView: "external-front",
    defaultPreset: "skeleton",
    cameraTarget: [0, -0.25, 0.04],
    cameraDistance: 1.0,
    seedLabels: ["Pelvis", "Uterus region"],
    structures: [
      { name: "Uterus / cervix", note: "ANC / gyn exam" },
      { name: "Adnexa", note: "Cyst / ectopic" },
      { name: "Pelvic bones", note: "CPD / trauma" },
      { name: "Perineum", note: "Delivery / tears" },
    ],
  },
  psychiatry: {
    specialtyId: "psychiatry",
    title: "Brain & behavior map",
    subtitle: "Cortical regions relevant to mood, cognition, risk",
    focusKeywords: ["brain", "frontal", "temporal", "limbic", "skull"],
    defaultView: "external-front",
    defaultPreset: "nervous",
    cameraTarget: [0, 0.65, 0],
    cameraDistance: 0.75,
    seedLabels: ["Frontal lobe", "Temporal lobe"],
    structures: [
      { name: "Frontal lobe", note: "Executive / mood" },
      { name: "Temporal / limbic", note: "Memory / affect" },
      { name: "Brainstem", note: "Arousal / meds risk" },
    ],
  },
  emergency: {
    specialtyId: "emergency",
    title: "Trauma & ABCDE map",
    subtitle: "Airway, chest, abdomen, pelvis, long bones",
    focusKeywords: ["skull", "cervical", "rib", "lung", "abdomen", "pelvis", "femur", "spine"],
    defaultView: "external-front",
    defaultPreset: "skeleton",
    cameraTarget: [0, 0.1, 0],
    cameraDistance: 2.3,
    seedLabels: ["Airway / C-spine", "Chest", "Pelvis"],
    structures: [
      { name: "C-spine / airway", note: "ATLS primary survey" },
      { name: "Chest", note: "Tension / hemothorax" },
      { name: "Abdomen / pelvis", note: "Bleeding sources" },
      { name: "Long bones", note: "Open fracture / MLC" },
    ],
  },
  icu: {
    specialtyId: "icu",
    title: "Critical care anatomy",
    subtitle: "Airway, lungs, heart, access & organ beds",
    focusKeywords: ["trachea", "lung", "heart", "aorta", "kidney", "vein", "artery"],
    defaultView: "external-front",
    defaultPreset: "vascular",
    cameraTarget: [0, 0.25, 0.05],
    cameraDistance: 1.2,
    seedLabels: ["Airway", "Heart", "Central line zone"],
    structures: [
      { name: "Airway / lungs", note: "Ventilation" },
      { name: "Heart / vessels", note: "Shock / pressors" },
      { name: "Kidneys", note: "AKI / CRRT" },
      { name: "Access sites", note: "CVC / arterial line" },
    ],
  },
  dental: {
    specialtyId: "dental",
    title: "Oral & maxillofacial anatomy",
    subtitle: "Jaw, teeth arches, TMJ & facial bones",
    focusKeywords: ["mandible", "maxilla", "tooth", "teeth", "jaw", "temporal", "face", "zygoma"],
    defaultView: "external-front",
    defaultPreset: "skeleton",
    cameraTarget: [0, 0.58, 0.12],
    cameraDistance: 0.55,
    seedLabels: ["Mandible", "Maxilla", "TMJ"],
    structures: [
      { name: "Dental arches", note: "FDI charting" },
      { name: "Mandible / maxilla", note: "Fracture / implant" },
      { name: "TMJ", note: "Pain / dysfunction" },
      { name: "Sinuses", note: "Oro-antral risk" },
    ],
  },
  urology: {
    specialtyId: "urology",
    title: "Urologic anatomy",
    subtitle: "Kidneys, bladder, prostate & male pelvis",
    focusKeywords: ["kidney", "bladder", "prostate", "urethra", "pelvis", "ureter"],
    defaultView: "external-front",
    defaultPreset: "inside",
    cameraTarget: [0, -0.2, 0.04],
    cameraDistance: 1.05,
    seedLabels: ["Kidney", "Bladder", "Prostate region"],
    structures: [
      { name: "Kidneys / ureters", note: "Stones / obstruction" },
      { name: "Bladder", note: "Hematuria / tumor" },
      { name: "Prostate", note: "BPH / CaP" },
      { name: "Urethra", note: "Stricture / trauma" },
    ],
  },
  endocrinology: {
    specialtyId: "endocrinology",
    title: "Endocrine anatomy",
    subtitle: "Thyroid, adrenals, pancreas & metabolic organs",
    focusKeywords: ["thyroid", "adrenal", "pancrea", "pituitary", "neck", "kidney"],
    defaultView: "external-front",
    defaultPreset: "inside",
    cameraTarget: [0, 0.45, 0.06],
    cameraDistance: 1.3,
    seedLabels: ["Thyroid", "Adrenals", "Pancreas"],
    structures: [
      { name: "Thyroid / neck", note: "Goiter / nodules" },
      { name: "Pancreas", note: "Diabetes / insulin" },
      { name: "Adrenals", note: "Cushing / Addison" },
      { name: "Pituitary zone", note: "Hormone axis" },
    ],
  },
  rheumatology: {
    specialtyId: "rheumatology",
    title: "Joints & connective tissue",
    subtitle: "Synovial joints, hands, spine for arthritis scoring",
    focusKeywords: ["joint", "hand", "wrist", "knee", "spine", "finger", "toe", "sacro"],
    defaultView: "external-front",
    defaultPreset: "skeleton",
    cameraTarget: [0, 0.05, 0],
    cameraDistance: 2.0,
    seedLabels: ["Hands", "Knees", "Spine"],
    structures: [
      { name: "Small joints (hands)", note: "RA / DAS28" },
      { name: "Knees / hips", note: "OA / effusion" },
      { name: "Spine / SI joints", note: "AxSpA" },
      { name: "Soft tissue", note: "Myositis / vasculitis" },
    ],
  },
  general_medicine: {
    specialtyId: "general_medicine",
    title: "Systemic body map",
    subtitle: "Full adult exam — CVS, RS, abdomen, CNS landmarks",
    focusKeywords: ["heart", "lung", "liver", "abdomen", "brain", "kidney"],
    defaultView: "external-front",
    defaultPreset: "surface",
    cameraTarget: [0, 0.1, 0],
    cameraDistance: 2.5,
    seedLabels: ["Heart", "Lungs", "Abdomen"],
    structures: [
      { name: "CVS", note: "BP / murmur" },
      { name: "RS", note: "Breath sounds" },
      { name: "Abdomen", note: "Organomegaly" },
      { name: "CNS", note: "Focal signs" },
    ],
  },
  physiotherapy: {
    specialtyId: "physiotherapy",
    title: "Rehab & movement anatomy",
    subtitle: "Muscle groups, joints & gait chain",
    focusKeywords: ["muscle", "quad", "hamstring", "glute", "spine", "shoulder", "knee", "ankle"],
    defaultView: "external-front",
    defaultPreset: "surface",
    cameraTarget: [0, 0, 0],
    cameraDistance: 2.3,
    seedLabels: ["Knee extensors", "Lumbar", "Shoulder"],
    structures: [
      { name: "Core / lumbar", note: "Back pain rehab" },
      { name: "Lower limb chain", note: "Gait / post-TKR" },
      { name: "Shoulder girdle", note: "Frozen shoulder" },
      { name: "Balance centers", note: "Stroke rehab" },
    ],
  },
  anesthesia: {
    specialtyId: "anesthesia",
    title: "Airway & anesthesia map",
    subtitle: "Airway, spine levels, regional block landmarks",
    focusKeywords: ["trachea", "larynx", "cervical", "spine", "vertebra", "rib", "nerve"],
    defaultView: "external-front",
    defaultPreset: "nervous",
    cameraTarget: [0, 0.5, 0.08],
    cameraDistance: 1.0,
    seedLabels: ["Airway", "C-spine", "Lumbar block zone"],
    structures: [
      { name: "Airway", note: "Mallampati / intubation" },
      { name: "C-spine", note: "Difficult airway" },
      { name: "Neuraxial levels", note: "Spinal / epidural" },
      { name: "Peripheral nerves", note: "Regional blocks" },
    ],
  },
  radiology: {
    specialtyId: "radiology",
    title: "Imaging anatomy atlas",
    subtitle: "Cross-sectional landmarks for report correlation",
    focusKeywords: ["brain", "lung", "liver", "spine", "pelvis", "heart", "kidney"],
    defaultView: "external-front",
    defaultPreset: "inside",
    cameraTarget: [0, 0.1, 0],
    cameraDistance: 2.2,
    seedLabels: ["Brain", "Chest", "Abdomen"],
    structures: [
      { name: "Neuro", note: "CT/MRI brain" },
      { name: "Thorax", note: "CXR / CT chest" },
      { name: "Abdomen", note: "USG / CT AP" },
      { name: "MSK", note: "X-ray / MRI" },
    ],
  },
  neonatology: {
    specialtyId: "neonatology",
    title: "Newborn anatomy focus",
    subtitle: "Airway, chest, abdomen, fontanelle landmarks",
    focusKeywords: ["skull", "lung", "heart", "abdomen", "umbilic"],
    defaultView: "external-front",
    defaultPreset: "surface",
    cameraTarget: [0, 0.25, 0],
    cameraDistance: 1.8,
    seedLabels: ["Head", "Chest", "Abdomen"],
    structures: [
      { name: "Fontanelle / head", note: "Jaundice / trauma" },
      { name: "Chest / airway", note: "RDS / TTN" },
      { name: "Abdomen", note: "NEC / feeding" },
      { name: "Umbilicus", note: "Infection / hernia" },
    ],
  },
  plastic_surgery: {
    specialtyId: "plastic_surgery",
    title: "Reconstructive surface map",
    subtitle: "Soft tissue units, flaps & burn TBSA regions",
    focusKeywords: ["skin", "face", "hand", "muscle", "breast", "scalp"],
    defaultView: "external-front",
    defaultPreset: "surface",
    cameraTarget: [0, 0.2, 0.05],
    cameraDistance: 2.0,
    seedLabels: ["Face units", "Hand", "Donor site"],
    structures: [
      { name: "Facial subunits", note: "Aesthetic / trauma" },
      { name: "Hand", note: "Tendon / flap" },
      { name: "Trunk donor sites", note: "Graft / flap harvest" },
      { name: "Burn regions", note: "TBSA mapping" },
    ],
  },
  neurosurgery: {
    specialtyId: "neurosurgery",
    title: "Neurosurgical anatomy",
    subtitle: "Skull, brain, spine corridors for operative planning",
    focusKeywords: ["skull", "brain", "spine", "vertebra", "cervical", "lumbar", "dura"],
    defaultView: "external-front",
    defaultPreset: "nervous",
    cameraTarget: [0, 0.55, 0],
    cameraDistance: 1.0,
    seedLabels: ["Skull vault", "Cervical spine", "Lumbar disc"],
    structures: [
      { name: "Cranial vault", note: "Craniotomy planning" },
      { name: "Cervical / lumbar", note: "Disc / fusion" },
      { name: "Neural foramina", note: "Root compression" },
    ],
  },
  cardiac_surgery: {
    specialtyId: "cardiac_surgery",
    title: "CTVS operative anatomy",
    subtitle: "Heart, great vessels, sternum & graft conduits",
    focusKeywords: ["heart", "aorta", "sternum", "coronar", "pulmonary", "vena", "rib"],
    defaultView: "external-front",
    defaultPreset: "vascular",
    cameraTarget: [0.02, 0.3, 0.08],
    cameraDistance: 0.9,
    seedLabels: ["Heart", "Aorta", "Sternum"],
    structures: [
      { name: "Heart / coronaries", note: "CABG targets" },
      { name: "Valves / aorta", note: "AVR / root" },
      { name: "Sternum / mediastinum", note: "Approach" },
      { name: "Conduit beds", note: "IMA / SVG" },
    ],
  },
  hepatology: {
    specialtyId: "hepatology",
    title: "Hepatobiliary anatomy",
    subtitle: "Liver lobes, portal tract & biliary tree region",
    focusKeywords: ["liver", "hepatic", "gall", "biliary", "portal", "spleen"],
    defaultView: "external-front",
    defaultPreset: "inside",
    cameraTarget: [0.08, 0.12, 0.05],
    cameraDistance: 1.0,
    seedLabels: ["Liver", "Gallbladder region", "Spleen"],
    structures: [
      { name: "Liver lobes", note: "Cirrhosis / HCC" },
      { name: "Biliary tree", note: "Cholestasis" },
      { name: "Portal circulation", note: "Portal HTN" },
      { name: "Spleen", note: "Hypersplenism" },
    ],
  },
  hematology: {
    specialtyId: "hematology",
    title: "Hematologic organ map",
    subtitle: "Marrow sites, spleen, nodes & vascular beds",
    focusKeywords: ["spleen", "bone", "lymph", "liver", "marrow", "sternum", "iliac"],
    defaultView: "external-front",
    defaultPreset: "skeleton",
    cameraTarget: [0, 0.1, 0],
    cameraDistance: 2.0,
    seedLabels: ["Spleen", "Marrow sites", "Nodes"],
    structures: [
      { name: "Bone marrow beds", note: "Biopsy / leukemia" },
      { name: "Spleen", note: "Splenomegaly" },
      { name: "Lymph nodes", note: "Lymphoma staging" },
      { name: "Vessels", note: "Thrombosis / bleed" },
    ],
  },
  infectious_disease: {
    specialtyId: "infectious_disease",
    title: "Infection focus map",
    subtitle: "Common foci — lungs, CNS, abdomen, skin, lines",
    focusKeywords: ["lung", "brain", "liver", "skin", "kidney", "heart", "abdomen"],
    defaultView: "external-front",
    defaultPreset: "inside",
    cameraTarget: [0, 0.1, 0],
    cameraDistance: 2.2,
    seedLabels: ["Lungs", "CNS", "Abdomen"],
    structures: [
      { name: "Lungs", note: "Pneumonia / TB" },
      { name: "CNS", note: "Meningitis" },
      { name: "Abdomen / GU", note: "Intra-abdominal / UTI" },
      { name: "Skin / lines", note: "Cellulitis / CRBSI" },
    ],
  },
};

export function getSpecialtyAnatomy(id: SpecialtyId): SpecialtyAnatomyFocus {
  return SPECIALTY_ANATOMY[id];
}

/** Build demo seed markers from specialty focus (region ids are stable slugs) */
export function specialtySeedMarkers(id: SpecialtyId): BodyMarker[] {
  const focus = SPECIALTY_ANATOMY[id];
  return focus.seedLabels.map((label, i) => ({
    regionId: `specialty-${id}-seed-${i}`,
    label,
    view: focus.defaultView,
    meshType: "focus",
  }));
}
