import type { SpecialtyDefinition, SpecialtyId } from "./types";

/** Canonical specialty catalog — drives doctor specialty desks when admin assigns specialty */
export const SPECIALTY_CATALOG: Record<SpecialtyId, SpecialtyDefinition> = {
  ophthalmology: {
    id: "ophthalmology",
    name: "Ophthalmology",
    shortName: "Eye",
    department: "Eye Care",
    icon: "Eye",
    accent: "#1D6B8A",
    accentSoft: "#E4F2F7",
    tagline: "Vision, anterior segment, retina & ocular surgery",
    defaultFee: 900,
    unitLabel: "Eye OPD / OT",
    commonPresentations: [
      "Blurred vision",
      "Red eye",
      "Cataract",
      "Glaucoma follow-up",
      "Diabetic retinopathy",
      "Refractive error",
      "Foreign body",
      "Dry eye",
    ],
    modules: [
      {
        id: "va",
        kind: "visual_acuity",
        title: "Visual acuity",
        description: "UCVA / BCVA for OD and OS",
        fields: [
          { id: "ucva_od", label: "UCVA OD", type: "text", placeholder: "6/6" },
          { id: "ucva_os", label: "UCVA OS", type: "text", placeholder: "6/9" },
          { id: "bcva_od", label: "BCVA OD", type: "text", placeholder: "6/6" },
          { id: "bcva_os", label: "BCVA OS", type: "text", placeholder: "6/6" },
          { id: "near_od", label: "Near OD", type: "text", placeholder: "N6" },
          { id: "near_os", label: "Near OS", type: "text", placeholder: "N6" },
          {
            id: "pinhole",
            label: "Pinhole improvement",
            type: "select",
            options: ["Yes", "No", "Partial"],
          },
        ],
      },
      {
        id: "refraction",
        kind: "exam",
        title: "Refraction & IOP",
        description: "Sphere/cylinder/axis and tonometry",
        fields: [
          { id: "sph_od", label: "Sphere OD", type: "text", unit: "D" },
          { id: "cyl_od", label: "Cylinder OD", type: "text", unit: "D" },
          { id: "axis_od", label: "Axis OD", type: "number", unit: "°" },
          { id: "sph_os", label: "Sphere OS", type: "text", unit: "D" },
          { id: "cyl_os", label: "Cylinder OS", type: "text", unit: "D" },
          { id: "axis_os", label: "Axis OS", type: "number", unit: "°" },
          { id: "iop_od", label: "IOP OD", type: "number", unit: "mmHg" },
          { id: "iop_os", label: "IOP OS", type: "number", unit: "mmHg" },
          {
            id: "method",
            label: "IOP method",
            type: "select",
            options: ["NCT", "Goldmann", "Tono-Pen", "iCare"],
          },
        ],
      },
      {
        id: "slit_lamp",
        kind: "exam",
        title: "Slit-lamp & fundus",
        description: "Anterior segment and posterior pole",
        fields: [
          {
            id: "lids",
            label: "Lids / lashes",
            type: "textarea",
            placeholder: "Normal / blepharitis…",
          },
          { id: "conjunctiva", label: "Conjunctiva", type: "textarea" },
          { id: "cornea", label: "Cornea", type: "textarea" },
          { id: "ac", label: "Anterior chamber", type: "textarea" },
          { id: "iris", label: "Iris / pupil", type: "textarea" },
          { id: "lens", label: "Lens", type: "textarea", placeholder: "NS II / PSC…" },
          { id: "vitreous", label: "Vitreous", type: "textarea" },
          { id: "disc", label: "Optic disc (CDR)", type: "textarea" },
          { id: "macula", label: "Macula", type: "textarea" },
          { id: "periphery", label: "Retinal periphery", type: "textarea" },
        ],
      },
      {
        id: "ophtho_orders",
        kind: "orders",
        title: "Eye investigations",
        description: "OCT, fields, biometry, imaging",
        orderSets: [
          {
            id: "oct",
            name: "Retina / glaucoma imaging",
            category: "imaging",
            items: ["OCT macula", "OCT RNFL", "Fundus photo", "FFA", "ICG"],
          },
          {
            id: "fields",
            name: "Visual fields & biometry",
            category: "imaging",
            items: [
              "Humphrey 24-2",
              "Humphrey 10-2",
              "A-scan biometry",
              "IOL Master",
              "Corneal topography",
            ],
          },
        ],
      },
      {
        id: "ophtho_proc",
        kind: "procedures",
        title: "Eye procedures",
        description: "Minor OT and major surgery",
        procedures: [
          { id: "yag", name: "YAG capsulotomy", durationMin: 20, requiresConsent: true },
          { id: "inj", name: "Intravitreal injection", durationMin: 30, requiresConsent: true },
          {
            id: "cat",
            name: "Phaco + IOL",
            durationMin: 45,
            requiresConsent: true,
            implantPossible: true,
          },
          { id: "trab", name: "Trabeculectomy", durationMin: 90, requiresConsent: true },
          { id: "pter", name: "Pterygium excision", durationMin: 40, requiresConsent: true },
          { id: "chal", name: "Chalazion I&D", durationMin: 25, requiresConsent: true },
        ],
      },
    ],
  },

  cardiology: {
    id: "cardiology",
    name: "Cardiology",
    shortName: "Heart",
    department: "Cardiac Sciences",
    icon: "Heart",
    accent: "#B33A4A",
    accentSoft: "#F8E8EA",
    tagline: "Chest pain, heart failure, arrhythmias & interventions",
    defaultFee: 1800,
    unitLabel: "Cardiac OPD / CCU",
    commonPresentations: [
      "Chest pain",
      "Palpitations",
      "Dyspnea",
      "Hypertension",
      "Heart failure follow-up",
      "Post-MI review",
      "Syncope",
      "Pre-op cardiac clearance",
    ],
    modules: [
      {
        id: "cardio_intake",
        kind: "intake",
        title: "Cardiac history",
        description: "Risk factors and symptom profile",
        fields: [
          {
            id: "chest_pain",
            label: "Chest pain character",
            type: "select",
            options: ["None", "Typical angina", "Atypical", "Non-cardiac"],
          },
          {
            id: "nyha",
            label: "NYHA class",
            type: "select",
            options: ["I", "II", "III", "IV"],
          },
          {
            id: "ccs",
            label: "CCS angina class",
            type: "select",
            options: ["0", "I", "II", "III", "IV"],
          },
          {
            id: "risks",
            label: "Risk factors",
            type: "multiselect",
            options: ["DM", "HTN", "Dyslipidemia", "Smoking", "Family Hx CAD", "Obesity", "CKD"],
          },
          { id: "prior_mi", label: "Prior MI / PCI / CABG", type: "textarea" },
          { id: "devices", label: "Devices (PPM/ICD/CRT)", type: "text" },
        ],
      },
      {
        id: "cardio_exam",
        kind: "exam",
        title: "Cardiac exam",
        description: "JVP, heart sounds, edema",
        fields: [
          {
            id: "jvp",
            label: "JVP",
            type: "select",
            options: ["Normal", "Elevated", "Not assessed"],
          },
          { id: "s1s2", label: "S1 / S2", type: "text" },
          { id: "murmur", label: "Murmur", type: "textarea" },
          {
            id: "edema",
            label: "Pedal edema",
            type: "select",
            options: ["None", "1+", "2+", "3+", "4+"],
          },
          { id: "lungs", label: "Lung bases", type: "text" },
          {
            id: "hr_rhythm",
            label: "Heart rate / rhythm",
            type: "text",
            placeholder: "78 bpm regular",
          },
        ],
      },
      {
        id: "ecg_mod",
        kind: "ecg",
        title: "ECG interpretation",
        description: "12-lead ECG findings",
        fields: [
          { id: "rate", label: "Rate", type: "number", unit: "bpm" },
          {
            id: "rhythm",
            label: "Rhythm",
            type: "select",
            options: ["Sinus", "AF", "AFlutter", "SVT", "VT", "Paced", "Other"],
          },
          { id: "axis", label: "Axis", type: "text" },
          { id: "intervals", label: "PR / QRS / QTc", type: "text" },
          { id: "st_t", label: "ST-T changes", type: "textarea" },
          { id: "impression", label: "ECG impression", type: "textarea", required: true },
        ],
      },
      {
        id: "echo_mod",
        kind: "echo",
        title: "Echocardiography",
        description: "Key echo measurements",
        fields: [
          { id: "ef", label: "LVEF", type: "number", unit: "%" },
          { id: "rwma", label: "RWMA", type: "textarea" },
          { id: "valves", label: "Valves", type: "textarea" },
          { id: "pasp", label: "PASP", type: "number", unit: "mmHg" },
          { id: "pericardium", label: "Pericardium", type: "text" },
          { id: "echo_imp", label: "Echo impression", type: "textarea" },
        ],
      },
      {
        id: "cardio_scores",
        kind: "scores",
        title: "Risk scores",
        description: "CHA₂DS₂-VASc, GRACE, Killip",
        scores: [
          {
            id: "chadsvasc",
            name: "CHA₂DS₂-VASc",
            description: "Stroke risk in AF",
            max: 9,
            items: [
              { id: "chf", label: "CHF / LV dysfunction", max: 1 },
              { id: "htn", label: "Hypertension", max: 1 },
              { id: "age75", label: "Age ≥75", max: 2 },
              { id: "dm", label: "Diabetes", max: 1 },
              { id: "stroke", label: "Prior stroke / TIA / TE", max: 2 },
              { id: "vasc", label: "Vascular disease", max: 1 },
              { id: "age65", label: "Age 65–74", max: 1 },
              { id: "sex", label: "Female sex", max: 1 },
            ],
          },
          {
            id: "killip",
            name: "Killip class",
            description: "AMI severity",
            max: 4,
            items: [
              { id: "k1", label: "I — no failure", max: 1 },
              { id: "k2", label: "II — mild failure / S3 / rales", max: 1 },
              { id: "k3", label: "III — pulmonary edema", max: 1 },
              { id: "k4", label: "IV — cardiogenic shock", max: 1 },
            ],
          },
        ],
      },
      {
        id: "cardio_orders",
        kind: "orders",
        title: "Cardiac orders",
        description: "Labs, stress, cath",
        orderSets: [
          {
            id: "card_labs",
            name: "Cardiac labs",
            category: "lab",
            items: [
              "Troponin I/T",
              "BNP / NT-proBNP",
              "Lipid profile",
              "HbA1c",
              "Electrolytes",
              "CBC",
            ],
          },
          {
            id: "card_img",
            name: "Cardiac imaging / tests",
            category: "imaging",
            items: ["ECG", "2D Echo", "TMT", "Holter 24h", "CT angio", "Coronary angiogram"],
          },
        ],
      },
      {
        id: "cardio_proc",
        kind: "procedures",
        title: "Cardiac procedures",
        description: "Cath lab & device",
        procedures: [
          { id: "cag", name: "Coronary angiogram", durationMin: 60, requiresConsent: true },
          {
            id: "pci",
            name: "PCI / stenting",
            durationMin: 90,
            requiresConsent: true,
            implantPossible: true,
          },
          {
            id: "ppm",
            name: "Pacemaker implant",
            durationMin: 120,
            requiresConsent: true,
            implantPossible: true,
          },
          { id: "tee", name: "TEE", durationMin: 45, requiresConsent: true },
        ],
      },
    ],
  },

  pediatrics: {
    id: "pediatrics",
    name: "Pediatrics",
    shortName: "Children",
    department: "Child Health",
    icon: "Baby",
    accent: "#2F6B4F",
    accentSoft: "#E6F3EC",
    tagline: "Growth, immunization, acute illness & developmental care",
    defaultFee: 800,
    unitLabel: "Pediatric OPD / Ward",
    commonPresentations: [
      "Fever",
      "Cough / cold",
      "Diarrhea",
      "Well-baby visit",
      "Immunization",
      "Failure to thrive",
      "Asthma / wheeze",
      "Developmental concern",
    ],
    modules: [
      {
        id: "peds_growth",
        kind: "growth",
        title: "Growth chart",
        description: "Anthropometry and percentiles",
        fields: [
          { id: "age_mo", label: "Age", type: "number", unit: "months" },
          { id: "weight", label: "Weight", type: "number", unit: "kg", required: true },
          { id: "height", label: "Length / Height", type: "number", unit: "cm", required: true },
          { id: "hc", label: "Head circumference", type: "number", unit: "cm" },
          { id: "bmi", label: "BMI", type: "number", unit: "kg/m²" },
          {
            id: "wt_pct",
            label: "Weight percentile",
            type: "select",
            options: ["<3rd", "3–15", "15–50", "50–85", "85–97", ">97"],
          },
          {
            id: "ht_pct",
            label: "Height percentile",
            type: "select",
            options: ["<3rd", "3–15", "15–50", "50–85", "85–97", ">97"],
          },
        ],
      },
      {
        id: "peds_imm",
        kind: "followup",
        title: "Immunization",
        description: "Vaccine status and due doses",
        fields: [
          {
            id: "imm_status",
            label: "Immunization status",
            type: "select",
            options: ["Up to date", "Delayed", "Partial", "Unknown"],
          },
          {
            id: "due",
            label: "Vaccines due today",
            type: "multiselect",
            options: [
              "BCG",
              "OPV/IPV",
              "DPT/Pentavalent",
              "Hib",
              "Hep B",
              "MMR",
              "Varicella",
              "Typhoid",
              "Influenza",
              "HPV",
            ],
          },
          { id: "imm_notes", label: "Notes / reactions", type: "textarea" },
        ],
      },
      {
        id: "peds_dev",
        kind: "exam",
        title: "Development milestones",
        description: "Age-appropriate milestones",
        fields: [
          {
            id: "gross_motor",
            label: "Gross motor",
            type: "select",
            options: ["Age-appropriate", "Delayed", "Advanced", "Not assessed"],
          },
          {
            id: "fine_motor",
            label: "Fine motor",
            type: "select",
            options: ["Age-appropriate", "Delayed", "Advanced", "Not assessed"],
          },
          {
            id: "language",
            label: "Language / social",
            type: "select",
            options: ["Age-appropriate", "Delayed", "Advanced", "Not assessed"],
          },
          { id: "dev_notes", label: "Developmental notes", type: "textarea" },
        ],
      },
      {
        id: "peds_scores",
        kind: "scores",
        title: "Pediatric scores",
        description: "APGAR / PEWS / dehydration",
        scores: [
          {
            id: "pews",
            name: "PEWS",
            description: "Pediatric early warning",
            max: 15,
            items: [
              { id: "behavior", label: "Behavior", max: 3 },
              { id: "cv", label: "Cardiovascular", max: 3 },
              { id: "resp", label: "Respiratory", max: 3 },
              { id: "neb", label: "Nebulizer / O₂", max: 3 },
              { id: "vomit", label: "Vomiting", max: 3 },
            ],
          },
        ],
      },
      {
        id: "peds_orders",
        kind: "orders",
        title: "Pediatric orders",
        description: "Age-appropriate labs & imaging",
        orderSets: [
          {
            id: "ped_labs",
            name: "Common pediatric labs",
            category: "lab",
            items: ["CBC", "CRP", "Blood culture", "Urine R/M + culture", "Electrolytes", "RBS"],
          },
        ],
      },
    ],
  },

  orthopedics: {
    id: "orthopedics",
    name: "Orthopedics",
    shortName: "Bones",
    department: "Orthopedics & Trauma",
    icon: "Bone",
    accent: "#6B4C2A",
    accentSoft: "#F3EBE0",
    tagline: "Fractures, joints, spine & sports injuries",
    defaultFee: 1200,
    unitLabel: "Ortho OPD / OT",
    commonPresentations: [
      "Knee pain",
      "Back pain",
      "Fracture follow-up",
      "Shoulder pain",
      "OA knee",
      "Sports injury",
      "Neck pain",
      "Post-op review",
    ],
    modules: [
      {
        id: "ortho_intake",
        kind: "intake",
        title: "MSK intake",
        description: "Mechanism, laterality, function",
        fields: [
          {
            id: "region",
            label: "Region",
            type: "select",
            options: [
              "Shoulder",
              "Elbow",
              "Wrist/Hand",
              "Hip",
              "Knee",
              "Ankle/Foot",
              "Cervical",
              "Lumbar",
              "Pelvis",
            ],
          },
          { id: "side", label: "Laterality", type: "laterality" },
          { id: "mechanism", label: "Mechanism of injury", type: "textarea" },
          {
            id: "onset",
            label: "Onset",
            type: "select",
            options: ["Acute", "Subacute", "Chronic"],
          },
          {
            id: "wt_bearing",
            label: "Weight bearing",
            type: "select",
            options: ["Full", "Partial", "Non", "N/A"],
          },
          {
            id: "neurovasc",
            label: "Neurovascular status",
            type: "text",
            placeholder: "Intact distal N/V",
          },
        ],
      },
      {
        id: "ortho_exam",
        kind: "exam",
        title: "Ortho exam",
        description: "ROM, strength, special tests",
        fields: [
          { id: "inspection", label: "Inspection", type: "textarea" },
          { id: "palpation", label: "Palpation", type: "textarea" },
          { id: "rom", label: "Range of motion", type: "textarea" },
          { id: "strength", label: "Power (MRC)", type: "text" },
          { id: "special", label: "Special tests", type: "textarea" },
          { id: "gait", label: "Gait", type: "text" },
        ],
      },
      {
        id: "fracture_mod",
        kind: "fracture",
        title: "Fracture classification",
        description: "AO / Gustilo / displacement",
        fields: [
          { id: "bone", label: "Bone / site", type: "text", required: true },
          {
            id: "pattern",
            label: "Pattern",
            type: "select",
            options: [
              "Transverse",
              "Oblique",
              "Spiral",
              "Comminuted",
              "Greenstick",
              "Pathologic",
              "Stress",
            ],
          },
          {
            id: "displacement",
            label: "Displacement",
            type: "select",
            options: ["Undisplaced", "Minimally", "Displaced", "Dislocated"],
          },
          {
            id: "open",
            label: "Open fracture grade",
            type: "select",
            options: ["Closed", "Gustilo I", "Gustilo II", "Gustilo IIIA", "IIIB", "IIIC"],
          },
          { id: "ao", label: "AO / OTA code", type: "text" },
        ],
      },
      {
        id: "ortho_scores",
        kind: "scores",
        title: "Functional scores",
        description: "VAS, Oxford, Oswestry",
        scores: [
          {
            id: "vas",
            name: "Pain VAS",
            description: "0–10 pain scale",
            max: 10,
            items: [{ id: "pain", label: "Current pain", max: 10 }],
          },
        ],
      },
      {
        id: "ortho_orders",
        kind: "orders",
        title: "Ortho imaging",
        description: "X-ray, CT, MRI",
        orderSets: [
          {
            id: "ortho_img",
            name: "MSK imaging",
            category: "imaging",
            items: ["X-ray AP/Lat", "X-ray oblique", "CT bone", "MRI", "USG soft tissue", "DEXA"],
          },
        ],
      },
      {
        id: "ortho_proc",
        kind: "procedures",
        title: "Ortho procedures",
        description: "Casting, arthroscopy, arthroplasty",
        procedures: [
          { id: "cast", name: "Cast / slab application", durationMin: 30, requiresConsent: true },
          {
            id: "crif",
            name: "CRIF / ORIF",
            durationMin: 120,
            requiresConsent: true,
            implantPossible: true,
          },
          {
            id: "acl",
            name: "ACL reconstruction",
            durationMin: 150,
            requiresConsent: true,
            implantPossible: true,
          },
          {
            id: "tkr",
            name: "Total knee replacement",
            durationMin: 120,
            requiresConsent: true,
            implantPossible: true,
          },
          {
            id: "thr",
            name: "Total hip replacement",
            durationMin: 120,
            requiresConsent: true,
            implantPossible: true,
          },
        ],
      },
    ],
  },

  neurology: {
    id: "neurology",
    name: "Neurology",
    shortName: "Neuro",
    department: "Neurosciences",
    icon: "Brain",
    accent: "#5B4B8A",
    accentSoft: "#EEEAF6",
    tagline: "Stroke, seizures, headache & neuromuscular disease",
    defaultFee: 1500,
    unitLabel: "Neuro OPD",
    commonPresentations: [
      "Headache",
      "Seizure",
      "Stroke / TIA",
      "Vertigo",
      "Neuropathy",
      "Parkinson follow-up",
    ],
    modules: [
      {
        id: "neuro_exam",
        kind: "exam",
        title: "Neurological exam",
        description: "Cranial nerves, motor, sensory, reflexes",
        fields: [
          { id: "mental", label: "Mental status", type: "text" },
          { id: "cn", label: "Cranial nerves", type: "textarea" },
          { id: "motor", label: "Motor (MRC)", type: "textarea" },
          { id: "sensory", label: "Sensory", type: "textarea" },
          { id: "reflexes", label: "Reflexes", type: "textarea" },
          { id: "cerebellar", label: "Cerebellar / gait", type: "textarea" },
          { id: "nihss", label: "NIHSS (if stroke)", type: "number" },
        ],
      },
      {
        id: "neuro_scores",
        kind: "scores",
        title: "Neuro scores",
        description: "GCS, NIHSS, mRS",
        scores: [
          {
            id: "gcs",
            name: "GCS",
            description: "Glasgow Coma Scale",
            max: 15,
            items: [
              { id: "eye", label: "Eye opening", max: 4 },
              { id: "verbal", label: "Verbal", max: 5 },
              { id: "motor", label: "Motor", max: 6 },
            ],
          },
        ],
      },
      {
        id: "neuro_orders",
        kind: "orders",
        title: "Neuro investigations",
        orderSets: [
          {
            id: "neuro_img",
            name: "Neuro imaging / EEG",
            category: "imaging",
            items: ["CT brain", "MRI brain", "MR angio", "EEG", "NCV / EMG", "LP"],
          },
        ],
      },
    ],
  },

  dermatology: {
    id: "dermatology",
    name: "Dermatology",
    shortName: "Skin",
    department: "Dermatology",
    icon: "Sparkles",
    accent: "#A65D3B",
    accentSoft: "#F8EEE8",
    tagline: "Rashes, infections, acne, pigment & procedures",
    defaultFee: 1000,
    unitLabel: "Derm OPD",
    commonPresentations: [
      "Acne",
      "Eczema",
      "Psoriasis",
      "Fungal infection",
      "Hair loss",
      "Pigmentation",
    ],
    modules: [
      {
        id: "derm_exam",
        kind: "exam",
        title: "Skin exam",
        description: "Morphology, distribution, mucosa",
        fields: [
          { id: "morphology", label: "Primary lesion", type: "text", required: true },
          { id: "distribution", label: "Distribution", type: "textarea" },
          { id: "color", label: "Color / surface", type: "text" },
          { id: "mucosa", label: "Mucosa / nails / hair", type: "textarea" },
          { id: "dermoscopy", label: "Dermoscopy", type: "textarea" },
        ],
      },
      {
        id: "derm_proc",
        kind: "procedures",
        title: "Derm procedures",
        procedures: [
          { id: "biopsy", name: "Skin biopsy", durationMin: 30, requiresConsent: true },
          { id: "cryo", name: "Cryotherapy", durationMin: 15, requiresConsent: true },
          { id: "laser", name: "Laser therapy", durationMin: 45, requiresConsent: true },
          { id: "chem", name: "Chemical peel", durationMin: 40, requiresConsent: true },
        ],
      },
    ],
  },

  ent: {
    id: "ent",
    name: "ENT",
    shortName: "ENT",
    department: "Otolaryngology",
    icon: "Ear",
    accent: "#3D6B6B",
    accentSoft: "#E6F1F1",
    tagline: "Ear, nose, throat & head-neck",
    defaultFee: 900,
    unitLabel: "ENT OPD / OT",
    commonPresentations: [
      "Ear pain",
      "Hearing loss",
      "Sinusitis",
      "Tonsillitis",
      "Vertigo",
      "Hoarseness",
    ],
    modules: [
      {
        id: "ent_exam",
        kind: "exam",
        title: "ENT exam",
        fields: [
          { id: "ear", label: "Ear (otoscopy)", type: "textarea" },
          { id: "nose", label: "Nose / sinuses", type: "textarea" },
          { id: "throat", label: "Throat / larynx", type: "textarea" },
          { id: "neck", label: "Neck nodes", type: "textarea" },
          { id: "audiometry", label: "Audiometry summary", type: "textarea" },
        ],
      },
      {
        id: "ent_proc",
        kind: "procedures",
        title: "ENT procedures",
        procedures: [
          { id: "wax", name: "Wax removal", durationMin: 15, requiresConsent: false },
          { id: "fess", name: "FESS", durationMin: 90, requiresConsent: true },
          { id: "tons", name: "Tonsillectomy", durationMin: 60, requiresConsent: true },
          { id: "tympano", name: "Tympanoplasty", durationMin: 120, requiresConsent: true },
        ],
      },
    ],
  },

  gastroenterology: {
    id: "gastroenterology",
    name: "Gastroenterology",
    shortName: "GI",
    department: "Digestive Sciences",
    icon: "Activity",
    accent: "#4A6B3D",
    accentSoft: "#EAF2E6",
    tagline: "Liver, pancreas, IBD & endoscopy",
    defaultFee: 1400,
    unitLabel: "GI OPD / Endoscopy",
    commonPresentations: ["Abdominal pain", "GERD", "IBS", "Jaundice", "IBD follow-up", "GI bleed"],
    modules: [
      {
        id: "gi_exam",
        kind: "exam",
        title: "GI assessment",
        fields: [
          { id: "abdomen", label: "Abdominal exam", type: "textarea" },
          { id: "stool", label: "Stool / bleeding history", type: "textarea" },
          { id: "liver", label: "Stigmata of liver disease", type: "textarea" },
          {
            id: "child_pugh",
            label: "Child-Pugh (if cirrhosis)",
            type: "select",
            options: ["N/A", "A", "B", "C"],
          },
        ],
      },
      {
        id: "gi_proc",
        kind: "procedures",
        title: "Endoscopy / procedures",
        procedures: [
          { id: "egd", name: "Upper GI endoscopy", durationMin: 30, requiresConsent: true },
          { id: "colo", name: "Colonoscopy", durationMin: 45, requiresConsent: true },
          { id: "ercp", name: "ERCP", durationMin: 90, requiresConsent: true },
          { id: "peg", name: "PEG placement", durationMin: 45, requiresConsent: true },
        ],
      },
    ],
  },

  nephrology: {
    id: "nephrology",
    name: "Nephrology",
    shortName: "Kidney",
    department: "Nephrology",
    icon: "Droplets",
    accent: "#2E5A8C",
    accentSoft: "#E5EEF6",
    tagline: "CKD, dialysis, electrolytes & transplant",
    defaultFee: 1400,
    unitLabel: "Nephro OPD / Dialysis",
    commonPresentations: [
      "CKD follow-up",
      "Hypertension",
      "Edema",
      "Dialysis review",
      "UTI",
      "Electrolyte imbalance",
    ],
    modules: [
      {
        id: "nephro_exam",
        kind: "exam",
        title: "Renal assessment",
        fields: [
          {
            id: "ckd_stage",
            label: "CKD stage",
            type: "select",
            options: ["1", "2", "3a", "3b", "4", "5", "Unknown"],
          },
          { id: "egfr", label: "eGFR", type: "number", unit: "mL/min" },
          { id: "creatinine", label: "Creatinine", type: "number", unit: "mg/dL" },
          { id: "access", label: "Dialysis access", type: "text" },
          { id: "dry_wt", label: "Dry weight", type: "number", unit: "kg" },
          { id: "urine", label: "Urine output / findings", type: "textarea" },
        ],
      },
      {
        id: "dialysis_mod",
        kind: "dialysis",
        title: "Dialysis prescription",
        fields: [
          {
            id: "modality",
            label: "Modality",
            type: "select",
            options: ["None", "HD", "HDF", "PD", "CRRT"],
          },
          { id: "freq", label: "Sessions / week", type: "number" },
          { id: "duration", label: "Duration", type: "number", unit: "hours" },
          { id: "uf", label: "UF goal", type: "number", unit: "L" },
          { id: "anticoag", label: "Anticoagulation", type: "text" },
        ],
      },
    ],
  },

  pulmonology: {
    id: "pulmonology",
    name: "Pulmonology",
    shortName: "Lungs",
    department: "Respiratory Medicine",
    icon: "Wind",
    accent: "#3A6A8A",
    accentSoft: "#E6F0F6",
    tagline: "Asthma, COPD, ILD, sleep & infection",
    defaultFee: 1200,
    unitLabel: "Pulmo OPD",
    commonPresentations: [
      "Asthma",
      "COPD",
      "Cough",
      "Breathlessness",
      "TB follow-up",
      "Sleep apnea",
    ],
    modules: [
      {
        id: "pulmo_exam",
        kind: "exam",
        title: "Respiratory exam",
        fields: [
          { id: "spo2", label: "SpO₂", type: "number", unit: "%" },
          { id: "rr", label: "Respiratory rate", type: "number", unit: "/min" },
          { id: "breath_sounds", label: "Breath sounds", type: "textarea" },
          { id: "peak_flow", label: "Peak flow", type: "number", unit: "L/min" },
          {
            id: "gold",
            label: "COPD GOLD (if applicable)",
            type: "select",
            options: ["N/A", "A", "B", "E"],
          },
          {
            id: "asthma_ctrl",
            label: "Asthma control",
            type: "select",
            options: ["Well controlled", "Partly", "Uncontrolled", "N/A"],
          },
        ],
      },
      {
        id: "pulmo_orders",
        kind: "orders",
        title: "Pulmo tests",
        orderSets: [
          {
            id: "pft",
            name: "Respiratory tests",
            category: "imaging",
            items: ["Spirometry", "DLCO", "Chest X-ray", "HRCT", "ABG", "Sleep study"],
          },
        ],
      },
    ],
  },

  oncology: {
    id: "oncology",
    name: "Oncology",
    shortName: "Cancer",
    department: "Oncology",
    icon: "Ribbon",
    accent: "#8A3D6B",
    accentSoft: "#F6E8F0",
    tagline: "Solid tumors, chemo day-care & supportive care",
    defaultFee: 2000,
    unitLabel: "Oncology / Day-care",
    commonPresentations: [
      "New diagnosis",
      "Chemo cycle",
      "Follow-up",
      "Pain / palliative",
      "Neutropenia",
    ],
    modules: [
      {
        id: "onco_staging",
        kind: "exam",
        title: "Cancer staging",
        fields: [
          { id: "primary", label: "Primary site", type: "text", required: true },
          { id: "histology", label: "Histology", type: "text" },
          { id: "tnm", label: "TNM / stage", type: "text" },
          {
            id: "performance",
            label: "ECOG / PS",
            type: "select",
            options: ["0", "1", "2", "3", "4"],
          },
          { id: "mets", label: "Metastases", type: "textarea" },
        ],
      },
      {
        id: "chemo_mod",
        kind: "chemo",
        title: "Chemo cycle",
        fields: [
          { id: "regimen", label: "Regimen", type: "text", required: true },
          { id: "cycle", label: "Cycle number", type: "number" },
          { id: "bsa", label: "BSA", type: "number", unit: "m²" },
          { id: "anc", label: "Pre-chemo ANC", type: "number" },
          { id: "toxicity", label: "Toxicity (CTCAE)", type: "textarea" },
        ],
      },
    ],
  },

  obgyn: {
    id: "obgyn",
    name: "Obstetrics & Gynecology",
    shortName: "OB-GYN",
    department: "Women's Health",
    icon: "HeartHandshake",
    accent: "#8A4A6B",
    accentSoft: "#F6EAF0",
    tagline: "Antenatal, delivery, gynecology & fertility",
    defaultFee: 1100,
    unitLabel: "OB-GYN OPD / L&D",
    commonPresentations: [
      "ANC visit",
      "Menstrual disorder",
      "PCOS",
      "Infertility",
      "Postnatal",
      "Fibroid",
    ],
    modules: [
      {
        id: "anc",
        kind: "antenatal",
        title: "Antenatal visit",
        fields: [
          { id: "lmp", label: "LMP", type: "date" },
          { id: "edd", label: "EDD", type: "date" },
          { id: "ga", label: "Gestational age", type: "text", placeholder: "28+3 weeks" },
          { id: "gravida", label: "G / P / A / L", type: "text" },
          { id: "bp", label: "BP", type: "text" },
          { id: "weight", label: "Weight", type: "number", unit: "kg" },
          { id: "fh", label: "Fundal height", type: "text" },
          { id: "fhr", label: "FHR", type: "number", unit: "bpm" },
          { id: "presentation", label: "Presentation", type: "text" },
          {
            id: "risk",
            label: "Risk category",
            type: "select",
            options: ["Low", "Moderate", "High"],
          },
        ],
      },
      {
        id: "gyn_exam",
        kind: "exam",
        title: "Gynecologic exam",
        fields: [
          { id: "pv", label: "PV findings", type: "textarea" },
          { id: "usg", label: "Pelvic USG", type: "textarea" },
          { id: "pap", label: "Pap / HPV", type: "text" },
        ],
      },
    ],
  },

  psychiatry: {
    id: "psychiatry",
    name: "Psychiatry",
    shortName: "Psych",
    department: "Mental Health",
    icon: "BrainCircuit",
    accent: "#5A5A8A",
    accentSoft: "#EEEEF6",
    tagline: "Mood, anxiety, psychosis & substance use",
    defaultFee: 1200,
    unitLabel: "Psychiatry OPD",
    commonPresentations: [
      "Depression",
      "Anxiety",
      "Insomnia",
      "Psychosis",
      "Substance use",
      "Follow-up",
    ],
    modules: [
      {
        id: "mse",
        kind: "mental_status",
        title: "Mental status exam",
        fields: [
          { id: "appearance", label: "Appearance / behavior", type: "textarea" },
          { id: "mood", label: "Mood / affect", type: "textarea" },
          { id: "thought", label: "Thought process / content", type: "textarea" },
          { id: "perception", label: "Perception", type: "textarea" },
          { id: "cognition", label: "Cognition / insight", type: "textarea" },
          { id: "risk", label: "Risk (self / others)", type: "textarea", required: true },
        ],
      },
      {
        id: "psych_scores",
        kind: "scores",
        title: "Screening scores",
        scores: [
          {
            id: "phq9",
            name: "PHQ-9",
            description: "Depression screen",
            max: 27,
            items: [
              { id: "q1", label: "Interest / pleasure", max: 3 },
              { id: "q2", label: "Feeling down", max: 3 },
              { id: "q3", label: "Sleep", max: 3 },
              { id: "q4", label: "Energy", max: 3 },
              { id: "q5", label: "Appetite", max: 3 },
              { id: "q6", label: "Self-worth", max: 3 },
              { id: "q7", label: "Concentration", max: 3 },
              { id: "q8", label: "Psychomotor", max: 3 },
              { id: "q9", label: "Suicidal thoughts", max: 3 },
            ],
          },
        ],
      },
    ],
  },

  emergency: {
    id: "emergency",
    name: "Emergency Medicine",
    shortName: "ER",
    department: "Emergency",
    icon: "Ambulance",
    accent: "#B33A3A",
    accentSoft: "#F8E8E8",
    tagline: "Triage, resuscitation & acute care",
    defaultFee: 0,
    unitLabel: "Emergency Department",
    commonPresentations: [
      "Trauma",
      "Chest pain",
      "Stroke",
      "Breathing difficulty",
      "Abdominal pain",
      "Poisoning",
    ],
    modules: [
      {
        id: "triage",
        kind: "triage",
        title: "ED triage",
        fields: [
          {
            id: "esi",
            label: "ESI / Triage level",
            type: "select",
            options: [
              "1 — Resuscitation",
              "2 — Emergent",
              "3 — Urgent",
              "4 — Less urgent",
              "5 — Non-urgent",
            ],
            required: true,
          },
          { id: "chief", label: "Chief complaint", type: "textarea", required: true },
          { id: "abcde", label: "ABCDE summary", type: "textarea" },
          { id: "allergies", label: "Allergies", type: "text" },
          { id: "mlc", label: "MLC / police intimation", type: "boolean" },
        ],
      },
      {
        id: "ed_scores",
        kind: "scores",
        title: "ED scores",
        scores: [
          {
            id: "news2",
            name: "NEWS2",
            description: "Early warning",
            max: 20,
            items: [
              { id: "rr", label: "Respiratory rate", max: 3 },
              { id: "spo2", label: "SpO₂", max: 3 },
              { id: "air", label: "Air / O₂", max: 2 },
              { id: "sbp", label: "Systolic BP", max: 3 },
              { id: "hr", label: "Pulse", max: 3 },
              { id: "avpu", label: "Consciousness", max: 3 },
              { id: "temp", label: "Temperature", max: 3 },
            ],
          },
        ],
      },
    ],
  },

  icu: {
    id: "icu",
    name: "Critical Care (ICU)",
    shortName: "ICU",
    department: "Critical Care",
    icon: "MonitorHeart",
    accent: "#6B2A3A",
    accentSoft: "#F4E6EA",
    tagline: "Ventilation, hemodynamics & organ support",
    defaultFee: 0,
    unitLabel: "ICU / HDU",
    commonPresentations: [
      "Respiratory failure",
      "Shock",
      "Sepsis",
      "Post-op ICU",
      "Multi-organ failure",
    ],
    modules: [
      {
        id: "vent",
        kind: "ventilator",
        title: "Ventilator settings",
        fields: [
          {
            id: "mode",
            label: "Mode",
            type: "select",
            options: ["Spontaneous", "CPAP", "BiPAP", "AC/VC", "SIMV", "PRVC", "HFOV"],
          },
          { id: "fio2", label: "FiO₂", type: "number", unit: "%" },
          { id: "peep", label: "PEEP", type: "number", unit: "cmH₂O" },
          { id: "tv", label: "Tidal volume", type: "number", unit: "mL" },
          { id: "rr_set", label: "Set RR", type: "number" },
          { id: "pip", label: "PIP / Pplat", type: "text" },
        ],
      },
      {
        id: "icu_scores",
        kind: "scores",
        title: "ICU scores",
        scores: [
          {
            id: "sofa",
            name: "SOFA",
            description: "Organ failure",
            max: 24,
            items: [
              { id: "resp", label: "Respiration", max: 4 },
              { id: "coag", label: "Coagulation", max: 4 },
              { id: "liver", label: "Liver", max: 4 },
              { id: "cv", label: "Cardiovascular", max: 4 },
              { id: "cns", label: "CNS", max: 4 },
              { id: "renal", label: "Renal", max: 4 },
            ],
          },
        ],
      },
    ],
  },

  dental: {
    id: "dental",
    name: "Dental / Oral Surgery",
    shortName: "Dental",
    department: "Dental",
    icon: "Smile",
    accent: "#3A6B8A",
    accentSoft: "#E6F0F6",
    tagline: "Restorative, endo, perio & oral surgery",
    defaultFee: 700,
    unitLabel: "Dental Clinic",
    commonPresentations: [
      "Toothache",
      "Caries",
      "Extraction",
      "Gum disease",
      "Root canal",
      "Implant consult",
    ],
    modules: [
      {
        id: "dental_chart",
        kind: "dental_chart",
        title: "Dental charting",
        fields: [
          { id: "fdi", label: "Tooth (FDI)", type: "text", placeholder: "16, 26…" },
          {
            id: "finding",
            label: "Finding",
            type: "select",
            options: [
              "Caries",
              "Pulpitis",
              "Abscess",
              "Periodontitis",
              "Fracture",
              "Missing",
              "Filled",
              "Crown",
            ],
          },
          { id: "peri", label: "Periodontal pocket", type: "text" },
          { id: "occlusion", label: "Occlusion notes", type: "textarea" },
          { id: "radio", label: "IOPA / OPG findings", type: "textarea" },
        ],
      },
      {
        id: "dental_proc",
        kind: "procedures",
        title: "Dental procedures",
        procedures: [
          { id: "ext", name: "Extraction", durationMin: 30, requiresConsent: true },
          { id: "rct", name: "Root canal treatment", durationMin: 60, requiresConsent: true },
          { id: "scale", name: "Scaling & polishing", durationMin: 40, requiresConsent: false },
          {
            id: "impl",
            name: "Dental implant",
            durationMin: 90,
            requiresConsent: true,
            implantPossible: true,
          },
        ],
      },
    ],
  },

  urology: {
    id: "urology",
    name: "Urology",
    shortName: "Uro",
    department: "Urology",
    icon: "Droplet",
    accent: "#2E6B6B",
    accentSoft: "#E6F1F1",
    tagline: "Stones, prostate, UTI & uro-oncology",
    defaultFee: 1300,
    unitLabel: "Urology OPD / OT",
    commonPresentations: [
      "Flank pain",
      "LUTS / BPH",
      "UTI",
      "Hematuria",
      "Stone follow-up",
      "Erectile dysfunction",
    ],
    modules: [
      {
        id: "uro_exam",
        kind: "exam",
        title: "Urology assessment",
        fields: [
          { id: "ipss", label: "IPSS score", type: "number" },
          { id: "psa", label: "PSA", type: "number", unit: "ng/mL" },
          { id: "dre", label: "DRE", type: "textarea" },
          { id: "stone", label: "Stone size / site", type: "text" },
          { id: "urine_flow", label: "Uroflow / PVR", type: "text" },
        ],
      },
      {
        id: "uro_proc",
        kind: "procedures",
        title: "Urology procedures",
        procedures: [
          { id: "urs", name: "URS / laser lithotripsy", durationMin: 90, requiresConsent: true },
          { id: "pcnl", name: "PCNL", durationMin: 120, requiresConsent: true },
          { id: "turp", name: "TURP", durationMin: 90, requiresConsent: true },
          { id: "cysto", name: "Cystoscopy", durationMin: 30, requiresConsent: true },
        ],
      },
    ],
  },

  endocrinology: {
    id: "endocrinology",
    name: "Endocrinology",
    shortName: "Endo",
    department: "Endocrinology",
    icon: "Syringe",
    accent: "#6B5A2A",
    accentSoft: "#F3EFE0",
    tagline: "Diabetes, thyroid, hormones & bone metabolism",
    defaultFee: 1400,
    unitLabel: "Endocrine OPD",
    commonPresentations: [
      "Diabetes",
      "Thyroid",
      "Obesity",
      "Osteoporosis",
      "PCOS endocrine",
      "Adrenal",
    ],
    modules: [
      {
        id: "endo_dm",
        kind: "exam",
        title: "Diabetes review",
        fields: [
          { id: "hba1c", label: "HbA1c", type: "number", unit: "%" },
          { id: "fbs", label: "FBS", type: "number", unit: "mg/dL" },
          { id: "ppbs", label: "PPBS", type: "number", unit: "mg/dL" },
          {
            id: "hypo",
            label: "Hypoglycemia episodes",
            type: "select",
            options: ["None", "Mild", "Severe"],
          },
          {
            id: "complications",
            label: "Complications screen",
            type: "multiselect",
            options: ["Retinopathy", "Nephropathy", "Neuropathy", "CAD", "PAD", "Foot ulcer"],
          },
          { id: "insulin", label: "Insulin / regimen", type: "textarea" },
        ],
      },
      {
        id: "endo_thyroid",
        kind: "exam",
        title: "Thyroid",
        fields: [
          { id: "tsh", label: "TSH", type: "number" },
          { id: "ft4", label: "Free T4", type: "number" },
          { id: "goiter", label: "Goiter / nodules", type: "textarea" },
        ],
      },
    ],
  },

  rheumatology: {
    id: "rheumatology",
    name: "Rheumatology",
    shortName: "Rheum",
    department: "Rheumatology",
    icon: "Hand",
    accent: "#6B3A5A",
    accentSoft: "#F4E8F0",
    tagline: "Arthritis, autoimmune & connective tissue disease",
    defaultFee: 1400,
    unitLabel: "Rheum OPD",
    commonPresentations: ["RA", "SLE", "OA", "Gout", "Ankylosing spondylitis", "Vasculitis"],
    modules: [
      {
        id: "rheum_exam",
        kind: "exam",
        title: "Joint exam",
        fields: [
          { id: "tjc", label: "Tender joint count", type: "number" },
          { id: "sjc", label: "Swollen joint count", type: "number" },
          { id: "das28", label: "DAS28", type: "number" },
          { id: "extra", label: "Extra-articular", type: "textarea" },
          { id: "dmard", label: "DMARD / biologic", type: "textarea" },
        ],
      },
    ],
  },

  general_medicine: {
    id: "general_medicine",
    name: "General Medicine",
    shortName: "Medicine",
    department: "Internal Medicine",
    icon: "Stethoscope",
    accent: "#1B3B2E",
    accentSoft: "#E8EFE6",
    tagline: "Adult medicine, multimorbidity & referrals",
    defaultFee: 600,
    unitLabel: "Medicine OPD",
    commonPresentations: [
      "Fever",
      "Hypertension",
      "Diabetes",
      "Anemia",
      "Infection",
      "General checkup",
      "Cough / breathlessness",
      "Abdominal pain",
      "Chest pain",
      "Weakness / fatigue",
    ],
    modules: [
      {
        id: "gm_intake",
        kind: "intake",
        title: "Visit",
        description: "Chief complaint and history — tap to chart",
        fields: [
          {
            id: "complaint",
            label: "Chief complaint",
            type: "textarea",
            required: true,
            placeholder: "Why is the patient here today?",
          },
          {
            id: "hpi",
            label: "History of present illness",
            type: "textarea",
            placeholder: "Onset, duration, severity, associated symptoms",
          },
          {
            id: "comorbid",
            label: "Comorbidities",
            type: "multiselect",
            options: [
              "Hypertension",
              "Type 2 diabetes",
              "CAD / IHD",
              "Asthma / COPD",
              "CKD",
              "Hypothyroidism",
              "Anemia",
              "None known",
            ],
          },
          {
            id: "meds_home",
            label: "Home medications",
            type: "multiselect",
            options: [
              "Antihypertensives",
              "Oral hypoglycemics / insulin",
              "Antiplatelets",
              "Statins",
              "Inhalers",
              "Thyroxine",
              "None / unknown",
            ],
          },
        ],
      },
      {
        id: "gm_vitals",
        kind: "vitals_extended",
        title: "Vitals",
        description: "Bedside numbers for this visit",
        fields: [
          { id: "bp_sys", label: "BP systolic", type: "number", unit: "mmHg" },
          { id: "bp_dia", label: "BP diastolic", type: "number", unit: "mmHg" },
          { id: "hr", label: "Heart rate", type: "number", unit: "/min" },
          { id: "rr", label: "Respiratory rate", type: "number", unit: "/min" },
          { id: "temp", label: "Temperature", type: "number", unit: "°C" },
          { id: "spo2", label: "SpO₂", type: "number", unit: "%" },
          { id: "weight", label: "Weight", type: "number", unit: "kg" },
          { id: "rbs", label: "RBS", type: "number", unit: "mg/dL" },
        ],
      },
      {
        id: "gm_exam",
        kind: "exam",
        title: "Exam",
        description: "Systemic examination — chart by exception",
        fields: [
          { id: "general", label: "General examination", type: "textarea" },
          { id: "cvs", label: "CVS", type: "textarea" },
          { id: "rs", label: "RS", type: "textarea" },
          { id: "abd", label: "Abdomen", type: "textarea" },
          { id: "cns", label: "CNS", type: "textarea" },
          {
            id: "provisional",
            label: "Provisional diagnosis",
            type: "textarea",
            required: true,
          },
        ],
      },
      {
        id: "gm_orders",
        kind: "orders",
        title: "Orders",
        description: "Labs and imaging for this visit",
        orderSets: [
          {
            id: "basic",
            name: "Basic workup",
            category: "lab",
            items: ["CBC", "RBS", "RFT", "LFT", "Electrolytes", "Urine R/M", "ECG", "Chest X-ray"],
          },
          {
            id: "fever",
            name: "Fever panel",
            category: "lab",
            items: ["CBC", "CRP", "Malaria smear", "Dengue NS1/IgM", "Widal", "Urine R/M", "Blood culture"],
          },
          {
            id: "dm_htn",
            name: "Diabetes / HTN follow-up",
            category: "lab",
            items: ["FBS", "PPBS", "HbA1c", "Lipid profile", "RFT", "Urine ACR", "ECG"],
          },
          {
            id: "imaging",
            name: "Imaging",
            category: "imaging",
            items: ["Chest X-ray", "USG abdomen", "Echo", "CT head"],
          },
        ],
      },
      {
        id: "gm_plan",
        kind: "followup",
        title: "Plan",
        description: "Advice, meds intent, and follow-up",
        fields: [
          {
            id: "advice",
            label: "Advice to patient",
            type: "multiselect",
            options: [
              "Hydration / rest",
              "Diet advice given",
              "BP home monitoring",
              "Sugar home monitoring",
              "Return if warning signs",
              "Refer to specialist",
              "Admit / observe",
            ],
          },
          {
            id: "rx_intent",
            label: "Treatment intent",
            type: "multiselect",
            options: [
              "Start / adjust antihypertensives",
              "Start / adjust antidiabetics",
              "Antibiotics",
              "Antipyretics / analgesics",
              "Nebulization / inhalers",
              "Iron / vitamins",
              "No new drugs",
            ],
          },
          {
            id: "followup",
            label: "Follow-up",
            type: "select",
            options: ["PRN", "3 days", "1 week", "2 weeks", "1 month", "With reports"],
          },
          {
            id: "plan_notes",
            label: "Plan notes",
            type: "textarea",
            placeholder: "Only if something is not covered above",
          },
        ],
      },
    ],
  },

  physiotherapy: {
    id: "physiotherapy",
    name: "Physiotherapy & Rehab",
    shortName: "PT",
    department: "Rehabilitation",
    icon: "Accessibility",
    accent: "#3D6B4A",
    accentSoft: "#E8F2EA",
    tagline: "Mobility, pain rehab & post-op recovery",
    defaultFee: 500,
    unitLabel: "Physio Gym",
    commonPresentations: [
      "Back pain",
      "Post-fracture rehab",
      "Stroke rehab",
      "Sports rehab",
      "Post-TKR",
    ],
    modules: [
      {
        id: "pt_exam",
        kind: "exam",
        title: "PT assessment",
        fields: [
          { id: "functional", label: "Functional goals", type: "textarea" },
          { id: "rom_pt", label: "ROM findings", type: "textarea" },
          { id: "strength_pt", label: "Strength", type: "textarea" },
          { id: "plan", label: "Therapy plan", type: "textarea" },
          { id: "sessions", label: "Sessions prescribed", type: "number" },
        ],
      },
    ],
  },

  anesthesia: {
    id: "anesthesia",
    name: "Anesthesiology",
    shortName: "Anesthesia",
    department: "Anesthesia",
    icon: "Syringe",
    accent: "#4A4A6B",
    accentSoft: "#ECECF4",
    tagline: "Pre-op assessment, anesthesia & pain",
    defaultFee: 0,
    unitLabel: "Pre-anesthesia Clinic / OT",
    commonPresentations: ["Pre-op PAC", "ASA assessment", "Pain consult", "Regional block"],
    modules: [
      {
        id: "pac",
        kind: "exam",
        title: "Pre-anesthesia checkup",
        fields: [
          {
            id: "asa",
            label: "ASA grade",
            type: "select",
            options: ["I", "II", "III", "IV", "V", "VI"],
            required: true,
          },
          { id: "airway", label: "Airway / Mallampati", type: "text" },
          { id: "comorbid", label: "Comorbidities", type: "textarea" },
          {
            id: "plan_anes",
            label: "Anesthesia plan",
            type: "select",
            options: ["GA", "Spinal", "Epidural", "Regional", "MAC", "Local"],
          },
          { id: "npo", label: "NPO status", type: "text" },
          { id: "consent_anes", label: "Consent obtained", type: "boolean" },
        ],
      },
    ],
  },

  radiology: {
    id: "radiology",
    name: "Radiology",
    shortName: "Radio",
    department: "Imaging",
    icon: "Scan",
    accent: "#3A5A6B",
    accentSoft: "#E6EEF2",
    tagline: "X-ray, CT, MRI, USG & reporting",
    defaultFee: 0,
    unitLabel: "Radiology / RIS",
    commonPresentations: ["X-ray report", "CT report", "MRI report", "USG report", "Intervention"],
    modules: [
      {
        id: "radio_report",
        kind: "imaging",
        title: "Imaging report",
        fields: [
          {
            id: "modality",
            label: "Modality",
            type: "select",
            options: ["X-ray", "USG", "CT", "MRI", "Mammography", "Fluoro", "Interventional"],
            required: true,
          },
          { id: "study", label: "Study / protocol", type: "text", required: true },
          { id: "technique", label: "Technique", type: "textarea" },
          { id: "findings", label: "Findings", type: "textarea", required: true },
          { id: "impression", label: "Impression", type: "textarea", required: true },
          { id: "critical", label: "Critical result", type: "boolean" },
        ],
      },
    ],
  },

  neonatology: {
    id: "neonatology",
    name: "Neonatology",
    shortName: "NICU",
    department: "Neonatology",
    icon: "Baby",
    accent: "#4A6B8A",
    accentSoft: "#E8F0F6",
    tagline: "Newborn care, NICU & lactation support",
    defaultFee: 0,
    unitLabel: "NICU / Nursery",
    commonPresentations: [
      "Well newborn",
      "Jaundice",
      "Prematurity",
      "Respiratory distress",
      "Sepsis screen",
    ],
    modules: [
      {
        id: "newborn",
        kind: "exam",
        title: "Newborn exam",
        fields: [
          { id: "gestation", label: "Gestation", type: "text", placeholder: "38+2 weeks" },
          { id: "bw", label: "Birth weight", type: "number", unit: "g" },
          { id: "apgar", label: "APGAR 1 / 5", type: "text" },
          { id: "bilirubin", label: "Bilirubin", type: "number", unit: "mg/dL" },
          {
            id: "feeding",
            label: "Feeding",
            type: "select",
            options: ["Breast", "Formula", "Mixed", "IV"],
          },
          { id: "screen", label: "Newborn screening", type: "textarea" },
        ],
      },
    ],
  },

  plastic_surgery: {
    id: "plastic_surgery",
    name: "Plastic & Reconstructive Surgery",
    shortName: "Plastic",
    department: "Plastic Surgery",
    icon: "Scissors",
    accent: "#6B4A5A",
    accentSoft: "#F4EAEF",
    tagline: "Burns, reconstruction, hand & aesthetics",
    defaultFee: 2000,
    unitLabel: "Plastic Surgery OPD / OT",
    commonPresentations: [
      "Burn",
      "Wound / flap",
      "Hand injury",
      "Scar revision",
      "Aesthetic consult",
    ],
    modules: [
      {
        id: "plastic_exam",
        kind: "exam",
        title: "Plastic surgery assessment",
        fields: [
          { id: "defect", label: "Defect / diagnosis", type: "textarea", required: true },
          { id: "tbsa", label: "TBSA % (burns)", type: "number" },
          { id: "plan_recon", label: "Reconstructive plan", type: "textarea" },
        ],
      },
      {
        id: "plastic_proc",
        kind: "procedures",
        title: "Plastic procedures",
        procedures: [
          { id: "graft", name: "Skin graft", durationMin: 90, requiresConsent: true },
          { id: "flap", name: "Flap reconstruction", durationMin: 180, requiresConsent: true },
          { id: "debride", name: "Debridement", durationMin: 45, requiresConsent: true },
        ],
      },
    ],
  },

  neurosurgery: {
    id: "neurosurgery",
    name: "Neurosurgery",
    shortName: "Neurosurg",
    department: "Neurosurgery",
    icon: "Brain",
    accent: "#4A2A6B",
    accentSoft: "#EFE8F4",
    tagline: "Brain, spine & peripheral nerve surgery",
    defaultFee: 2500,
    unitLabel: "Neurosurgery OPD / OT",
    commonPresentations: [
      "Disc prolapse",
      "Head injury",
      "Brain tumor",
      "Hydrocephalus",
      "Spine trauma",
    ],
    modules: [
      {
        id: "ns_exam",
        kind: "exam",
        title: "Neurosurgical assessment",
        fields: [
          { id: "gcs_ns", label: "GCS", type: "number" },
          { id: "neurodef", label: "Neuro deficit", type: "textarea" },
          { id: "imaging_ns", label: "Imaging summary", type: "textarea" },
          { id: "op_indication", label: "Operative indication", type: "textarea" },
        ],
      },
      {
        id: "ns_proc",
        kind: "operative",
        title: "Neurosurgery procedures",
        procedures: [
          { id: "crani", name: "Craniotomy", durationMin: 240, requiresConsent: true },
          {
            id: "discectomy",
            name: "Discectomy / fusion",
            durationMin: 180,
            requiresConsent: true,
            implantPossible: true,
          },
          {
            id: "vp",
            name: "VP shunt",
            durationMin: 90,
            requiresConsent: true,
            implantPossible: true,
          },
        ],
      },
    ],
  },

  cardiac_surgery: {
    id: "cardiac_surgery",
    name: "Cardiac Surgery",
    shortName: "CTVS",
    department: "Cardiothoracic Surgery",
    icon: "HeartPulse",
    accent: "#8A2A3A",
    accentSoft: "#F6E6EA",
    tagline: "CABG, valves & congenital heart surgery",
    defaultFee: 0,
    unitLabel: "CTVS OT / ICU",
    commonPresentations: ["CABG consult", "Valve disease", "Congenital", "Post-op follow-up"],
    modules: [
      {
        id: "ctvs_exam",
        kind: "exam",
        title: "CTVS assessment",
        fields: [
          { id: "indication", label: "Surgical indication", type: "textarea", required: true },
          { id: "euroscore", label: "EuroSCORE / STS", type: "text" },
          { id: "coronaries", label: "Coronary anatomy", type: "textarea" },
          { id: "valve", label: "Valve findings", type: "textarea" },
        ],
      },
      {
        id: "ctvs_proc",
        kind: "operative",
        title: "Cardiac surgery",
        procedures: [
          { id: "cabg", name: "CABG", durationMin: 300, requiresConsent: true },
          {
            id: "avr",
            name: "Valve replacement",
            durationMin: 300,
            requiresConsent: true,
            implantPossible: true,
          },
          { id: "asd", name: "ASD / VSD repair", durationMin: 240, requiresConsent: true },
        ],
      },
    ],
  },

  hepatology: {
    id: "hepatology",
    name: "Hepatology",
    shortName: "Liver",
    department: "Hepatology",
    icon: "Activity",
    accent: "#5A6B2A",
    accentSoft: "#EFF2E6",
    tagline: "Hepatitis, cirrhosis & liver transplant workup",
    defaultFee: 1500,
    unitLabel: "Hepatology Clinic",
    commonPresentations: [
      "Cirrhosis",
      "Viral hepatitis",
      "NAFLD",
      "Ascites",
      "Transplant evaluation",
    ],
    modules: [
      {
        id: "hep_exam",
        kind: "exam",
        title: "Liver assessment",
        fields: [
          {
            id: "etiology",
            label: "Etiology",
            type: "multiselect",
            options: ["HBV", "HCV", "Alcohol", "NAFLD/NASH", "Autoimmune", "Wilson", "Other"],
          },
          {
            id: "child",
            label: "Child-Pugh",
            type: "select",
            options: ["A", "B", "C"],
          },
          { id: "meld", label: "MELD", type: "number" },
          {
            id: "ascites",
            label: "Ascites",
            type: "select",
            options: ["None", "Mild", "Moderate", "Tense"],
          },
          {
            id: "he",
            label: "Hepatic encephalopathy",
            type: "select",
            options: ["None", "Grade 1–2", "Grade 3–4"],
          },
        ],
      },
    ],
  },

  hematology: {
    id: "hematology",
    name: "Hematology",
    shortName: "Heme",
    department: "Hematology",
    icon: "Droplets",
    accent: "#8A2A4A",
    accentSoft: "#F6E6EC",
    tagline: "Anemia, clotting, leukemia & transfusion",
    defaultFee: 1500,
    unitLabel: "Hematology Clinic",
    commonPresentations: [
      "Anemia",
      "Thrombocytopenia",
      "Leukemia / lymphoma",
      "Bleeding",
      "Thrombosis",
    ],
    modules: [
      {
        id: "heme_exam",
        kind: "exam",
        title: "Hematology workup",
        fields: [
          { id: "hb", label: "Hemoglobin", type: "number", unit: "g/dL" },
          { id: "wbc", label: "WBC", type: "number" },
          { id: "plt", label: "Platelets", type: "number" },
          { id: "peripheral", label: "Peripheral smear", type: "textarea" },
          { id: "coag", label: "Coagulation", type: "textarea" },
          { id: "transfusion", label: "Transfusion plan", type: "textarea" },
        ],
      },
    ],
  },

  infectious_disease: {
    id: "infectious_disease",
    name: "Infectious Diseases",
    shortName: "ID",
    department: "Infectious Diseases",
    icon: "Virus",
    accent: "#2A6B4A",
    accentSoft: "#E6F4EC",
    tagline: "Infections, antibiotics stewardship & tropical disease",
    defaultFee: 1200,
    unitLabel: "ID Clinic / Isolation",
    commonPresentations: [
      "Fever of unknown origin",
      "TB",
      "HIV",
      "Tropical fever",
      "Hospital infection",
      "Travel",
    ],
    modules: [
      {
        id: "id_exam",
        kind: "exam",
        title: "Infection assessment",
        fields: [
          { id: "syndrome", label: "Syndrome", type: "text", required: true },
          { id: "source", label: "Likely source", type: "textarea" },
          { id: "cultures", label: "Cultures pending / results", type: "textarea" },
          { id: "abx", label: "Antibiotic plan", type: "textarea" },
          {
            id: "isolation",
            label: "Isolation precautions",
            type: "select",
            options: ["None", "Contact", "Droplet", "Airborne"],
          },
        ],
      },
    ],
  },
};

export const SPECIALTY_LIST: SpecialtyDefinition[] = Object.values(SPECIALTY_CATALOG).sort((a, b) =>
  a.name.localeCompare(b.name),
);

export function getSpecialty(id: SpecialtyId): SpecialtyDefinition {
  return SPECIALTY_CATALOG[id];
}

export function specialtyName(id: SpecialtyId): string {
  return SPECIALTY_CATALOG[id]?.name ?? id;
}

/** Map free-text specialty labels (legacy) → SpecialtyId */
export function resolveSpecialtyId(label: string | null | undefined): SpecialtyId {
  if (!label) return "general_medicine";
  const n = label.trim().toLowerCase();
  const direct = SPECIALTY_LIST.find((s) => s.id === n || s.name.toLowerCase() === n);
  if (direct) return direct.id;

  const aliases: Record<string, SpecialtyId> = {
    "general physician": "general_medicine",
    "general medicine": "general_medicine",
    "internal medicine": "general_medicine",
    medicine: "general_medicine",
    eye: "ophthalmology",
    ophtha: "ophthalmology",
    ophthalmology: "ophthalmology",
    heart: "cardiology",
    cardiac: "cardiology",
    cardio: "cardiology",
    children: "pediatrics",
    paediatric: "pediatrics",
    pediatrics: "pediatrics",
    bones: "orthopedics",
    ortho: "orthopedics",
    orthopaedics: "orthopedics",
    orthopedics: "orthopedics",
    neuro: "neurology",
    derm: "dermatology",
    "ob/gyn": "obgyn",
    "ob-gyn": "obgyn",
    obstetrics: "obgyn",
    gynecology: "obgyn",
    gynaecology: "obgyn",
    er: "emergency",
    "emergency medicine": "emergency",
    "critical care": "icu",
    "intensive care": "icu",
    ent: "ent",
    "e.n.t": "ent",
    gi: "gastroenterology",
    gastro: "gastroenterology",
    pulmo: "pulmonology",
    respiratory: "pulmonology",
    nephro: "nephrology",
    onco: "oncology",
    psych: "psychiatry",
    mental: "psychiatry",
    dental: "dental",
    "oral surgery": "dental",
    physio: "physiotherapy",
    rehab: "physiotherapy",
    radio: "radiology",
    imaging: "radiology",
    nicu: "neonatology",
    newborn: "neonatology",
    ctvs: "cardiac_surgery",
    "cardio thoracic": "cardiac_surgery",
    "plastic surgery": "plastic_surgery",
    plastics: "plastic_surgery",
    "infectious disease": "infectious_disease",
    id: "infectious_disease",
  };

  for (const [key, id] of Object.entries(aliases)) {
    if (n.includes(key)) return id;
  }
  return "general_medicine";
}
