// Mock seed data for the Hospital Reception Management System
// All times are local (no TZ math) since this is a mock UI.

const today = new Date();
const pad = (n) => String(n).padStart(2, "0");
const todayStr = `${today.getFullYear()}-${pad(today.getMonth() + 1)}-${pad(
  today.getDate(),
)}`;

export const DOCTORS = [
  {
    id: "DOC-001",
    name: "Dr. Aarav Mehta",
    specialty: "General Medicine",
    room: "G-12",
    onDuty: true,
    shift: "08:00 – 16:00",
  },
  {
    id: "DOC-002",
    name: "Dr. Priya Nair",
    specialty: "Pediatrics",
    room: "P-04",
    onDuty: true,
    shift: "09:00 – 17:00",
  },
  {
    id: "DOC-003",
    name: "Dr. Rohan Bhatt",
    specialty: "Orthopedics",
    room: "O-21",
    onDuty: true,
    shift: "10:00 – 18:00",
  },
  {
    id: "DOC-004",
    name: "Dr. Sara Iyer",
    specialty: "Dermatology",
    room: "D-07",
    onDuty: false,
    shift: "Off today",
  },
  {
    id: "DOC-005",
    name: "Dr. Vikram Shah",
    specialty: "Cardiology",
    room: "C-15",
    onDuty: true,
    shift: "11:00 – 19:00",
  },
];

export const PATIENTS = [
  {
    id: "MRN-100231",
    name: "Anjali Krishnan",
    dob: "1989-03-14",
    gender: "Female",
    phone: "+91 98201 33421",
    email: "anjali.k@example.com",
    address: "12 Linking Road, Bandra W, Mumbai",
    emergency: { name: "Rahul Krishnan", phone: "+91 98201 33422", relation: "Spouse" },
    bloodGroup: "O+",
    allergies: "Penicillin",
    insurance: { provider: "Star Health", policyId: "SH-882-3341" },
    balance: 0,
    createdAt: "2024-08-12",
  },
  {
    id: "MRN-100232",
    name: "Mohammed Faraz",
    dob: "1972-11-02",
    gender: "Male",
    phone: "+91 99876 11203",
    email: "faraz72@example.com",
    address: "B-204, Marigold Apartments, Andheri E, Mumbai",
    emergency: { name: "Sana Faraz", phone: "+91 99876 11204", relation: "Daughter" },
    bloodGroup: "B+",
    allergies: "—",
    insurance: { provider: "HDFC Ergo", policyId: "HE-771-9921" },
    balance: 1450,
    createdAt: "2023-02-04",
  },
  {
    id: "MRN-100233",
    name: "Priyanka Desai",
    dob: "1996-07-21",
    gender: "Female",
    phone: "+91 97045 88210",
    email: "p.desai@example.com",
    address: "44 Pali Hill, Bandra W, Mumbai",
    emergency: { name: "Neha Desai", phone: "+91 97045 88211", relation: "Sister" },
    bloodGroup: "A-",
    allergies: "Sulfa drugs, Latex",
    insurance: { provider: "ICICI Lombard", policyId: "IL-664-2210" },
    balance: 0,
    createdAt: "2025-01-18",
  },
  {
    id: "MRN-100234",
    name: "Vijay Subramaniam",
    dob: "1958-09-30",
    gender: "Male",
    phone: "+91 98330 02145",
    email: "v.subramaniam@example.com",
    address: "9 Cuffe Parade, Colaba, Mumbai",
    emergency: { name: "Lakshmi S.", phone: "+91 98330 02146", relation: "Spouse" },
    bloodGroup: "AB+",
    allergies: "Aspirin",
    insurance: { provider: "Self-pay", policyId: "—" },
    balance: 2300,
    createdAt: "2022-06-09",
  },
  {
    id: "MRN-100235",
    name: "Kavya Reddy",
    dob: "2014-12-05",
    gender: "Female",
    phone: "+91 99000 71234",
    email: "—",
    address: "B-12 Lokhandwala, Andheri W, Mumbai",
    emergency: { name: "Anita Reddy", phone: "+91 99000 71234", relation: "Mother" },
    bloodGroup: "O-",
    allergies: "Peanuts",
    insurance: { provider: "Niva Bupa", policyId: "NB-441-5523" },
    balance: 0,
    createdAt: "2024-11-22",
  },
  {
    id: "MRN-100236",
    name: "Daniel Pereira",
    dob: "1981-04-17",
    gender: "Male",
    phone: "+91 98191 44021",
    email: "dan.p@example.com",
    address: "21 Carter Road, Bandra W, Mumbai",
    emergency: { name: "Maria Pereira", phone: "+91 98191 44022", relation: "Spouse" },
    bloodGroup: "A+",
    allergies: "—",
    insurance: { provider: "Star Health", policyId: "SH-220-7711" },
    balance: 500,
    createdAt: "2024-03-11",
  },
  {
    id: "MRN-100237",
    name: "Neha Gupta",
    dob: "1992-08-08",
    gender: "Female",
    phone: "+91 97744 33012",
    email: "neha.g@example.com",
    address: "11 Hiranandani, Powai, Mumbai",
    emergency: { name: "Rajiv Gupta", phone: "+91 97744 33013", relation: "Father" },
    bloodGroup: "B-",
    allergies: "Iodine",
    insurance: { provider: "Tata AIG", policyId: "TA-118-6677" },
    balance: 0,
    createdAt: "2025-05-29",
  },
  {
    id: "MRN-100238",
    name: "Arjun Malhotra",
    dob: "1965-01-23",
    gender: "Male",
    phone: "+91 99812 67342",
    email: "arjun.m@example.com",
    address: "5 Worli Sea Face, Worli, Mumbai",
    emergency: { name: "Pooja Malhotra", phone: "+91 99812 67343", relation: "Spouse" },
    bloodGroup: "O+",
    allergies: "—",
    insurance: { provider: "Care Health", policyId: "CH-993-2841" },
    balance: 0,
    createdAt: "2021-10-14",
  },
];

// Helper to build appointment times today
const at = (h, m) => `${pad(h)}:${pad(m)}`;

export const APPOINTMENTS = [
  {
    id: "APT-50011",
    patientId: "MRN-100231",
    doctorId: "DOC-001",
    date: todayStr,
    time: at(9, 0),
    type: "Follow-up",
    duration: 15,
    status: "checked-in",
    tokenNumber: 101,
    notes: "BP review",
  },
  {
    id: "APT-50012",
    patientId: "MRN-100232",
    doctorId: "DOC-001",
    date: todayStr,
    time: at(9, 20),
    type: "New",
    duration: 20,
    status: "in-progress",
    tokenNumber: 102,
    notes: "",
  },
  {
    id: "APT-50013",
    patientId: "MRN-100233",
    doctorId: "DOC-002",
    date: todayStr,
    time: at(10, 0),
    type: "New",
    duration: 20,
    status: "checked-in",
    tokenNumber: 201,
    notes: "",
  },
  {
    id: "APT-50014",
    patientId: "MRN-100235",
    doctorId: "DOC-002",
    date: todayStr,
    time: at(10, 30),
    type: "Follow-up",
    duration: 15,
    status: "scheduled",
    tokenNumber: null,
    notes: "Vaccination",
  },
  {
    id: "APT-50015",
    patientId: "MRN-100234",
    doctorId: "DOC-003",
    date: todayStr,
    time: at(11, 0),
    type: "New",
    duration: 30,
    status: "checked-in",
    tokenNumber: 301,
    notes: "Knee pain",
  },
  {
    id: "APT-50016",
    patientId: "MRN-100236",
    doctorId: "DOC-005",
    date: todayStr,
    time: at(11, 30),
    type: "Lab review",
    duration: 15,
    status: "scheduled",
    tokenNumber: null,
    notes: "ECG follow-up",
  },
  {
    id: "APT-50017",
    patientId: "MRN-100237",
    doctorId: "DOC-001",
    date: todayStr,
    time: at(12, 0),
    type: "New",
    duration: 20,
    status: "scheduled",
    tokenNumber: null,
    notes: "",
  },
  {
    id: "APT-50018",
    patientId: "MRN-100238",
    doctorId: "DOC-005",
    date: todayStr,
    time: at(14, 0),
    type: "Follow-up",
    duration: 20,
    status: "no-show",
    tokenNumber: null,
    notes: "",
  },
  {
    id: "APT-50019",
    patientId: "MRN-100233",
    doctorId: "DOC-003",
    date: todayStr,
    time: at(15, 0),
    type: "New",
    duration: 30,
    status: "scheduled",
    tokenNumber: null,
    notes: "Wrist sprain",
  },
];

export const VISIT_TYPES = ["New", "Follow-up", "Emergency", "Lab review"];
export const BLOOD_GROUPS = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];
export const GENDERS = ["Male", "Female", "Other"];

export const TIME_SLOTS = (() => {
  const out = [];
  for (let h = 8; h < 19; h++) {
    for (let m = 0; m < 60; m += 15) {
      out.push(`${pad(h)}:${pad(m)}`);
    }
  }
  return out;
})();

export const TODAY_STR = todayStr;
